### ISSUE TITLE
Dependency is not satisfiable: libmicrohttpd10

### ISSUE THREAD

**Issue by drandreaskrueger** [trezor/trezord-go#10]
> If you want to use TREZOR with different browsers, please [install TREZOR Bridge](https://wallet.trezor.io/#/).  
> trezor-bridge_1.2.1_amd64.deb

```
sudo gdebi trezor-bridge_1.2.1_amd64.deb 
Reading package lists... Done
Building dependency tree        
Reading state information... Done
Reading state information... Done
This package is uninstallable
Dependency is not satisfiable: libmicrohttpd10
```

```
sudo apt install libmicrohttpd10
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package libmicrohttpd10
```

```
uname -a
Linux ... 4.9.0-5-amd64 #1 SMP Debian 4.9.65-3+deb9u2 (2018-01-04) x86_64 GNU/Linux
```
current Debian has no libmicrohttpd10 yet?

https://packages.debian.org/search?keywords=libmicrohttpd10

**Comment by prusnak** [comment]
This is an issue for old bridge (trezord). Current version does not have this problem and will be deployed soon.

**Comment by prusnak** [comment]
If you can't wait for official release, build Bridge 2.0 from this repo.

**Comment by drandreaskrueger** [comment]
Ah no, I am patient.

Please don't close, until really solved; thanks. Or please ping this thread to alert me of the release; thanks.

**Comment by prusnak** [comment]
Bridge 2.x is already released and available from here: https://wallet.trezor.io/data/bridge/latest/index.html
