### ISSUE TITLE
FW update freezes on device with bootloader 1.6.0 when using Bridge on OS X

### ISSUE THREAD

**Issue by pankrats** [trezor/trezord-go#101]
operating system: OS X
Trezor fw version: 1.7.0 
bootloader: 1.6.0 
transport: Bridge

When trezord is running the firmware update gets stuck at INSTALLING...

It happens both on the wallet.trezor.io and via python-trezor. 

<img width="790" alt="screen shot 2018-09-18 at 15 56 24" src="https://user-images.githubusercontent.com/31442634/45692593-74c0a380-bb5b-11e8-9ea5-f15bb7d35d2b.png">

**Comment by karel-3d** [comment]
fixed in 2.0.24
