### ISSUE TITLE
Hyper-V VM Error LIBUSB_ERROR_OTHER

### ISSUE THREAD

**Issue by istrau2** [trezor/trezord-go#112]
I am on a windows machine and so I have to run the trezor emulator via VM. I am running like so: https://blogs.windows.com/buildingapps/2018/09/17/run-ubuntu-virtual-machines-made-even-easier-with-hyper-v-quick-create/

I have tried running trezord-go in two different ways:

1.  By following these instructions: https://github.com/trezor/trezord-go/#install-and-run-from-source
2.  By installing it from here: https://wallet.trezor.io/#/bridge

In both cases I am getting this error `LIBUSB_ERROR_OTHER`

Here is the output when I run `sudo service trezord status`
> ● trezord.service - TREZOR Bridge
>    Loaded: loaded (/usr/lib/systemd/system/trezord.service; enabled; vendor preset: enabled)
>    Active: failed (Result: exit-code) since Wed 2018-10-31 15:34:44 CDT; 20min ago
>   Process: 754 ExecStart=/usr/bin/trezord (code=exited, status=1/FAILURE)
>  Main PID: 754 (code=exited, status=1/FAILURE)
> 
> Oct 31 15:34:44 ishai-Virtual-Machine systemd[1]: Started TREZOR Bridge.
> Oct 31 15:34:44 ishai-Virtual-Machine trezord[754]: 2018/10/31 15:34:44 trezord is starting.
> Oct 31 15:34:44 ishai-Virtual-Machine trezord[754]: 2018/10/31 15:34:44 webusb: LIBUSB_ERROR_OTHER
> Oct 31 15:34:44 ishai-Virtual-Machine systemd[1]: trezord.service: Main process exited, code=exited, status=1/FAILURE
> Oct 31 15:34:44 ishai-Virtual-Machine systemd[1]: trezord.service: Failed with result 'exit-code'.

**Comment by karel-3d** [comment]
It seems to fail because there is no USB subsystem in the virtual machine.

Run bridge without usb, as is in the readme

`./trezord -e 21324 -u=false`

**Comment by prusnak** [comment]
Reopen when the suggestion above does not help

**Comment by istrau2** [comment]
@karel-3d thanks, that worked!

**Comment by prusnak** [comment]
No

**Comment by istrau2** [comment]
@prusnak Well, do you know why that might be happening? I run the emulator on the VM and then open the trezor wallet. It crashes.

**Comment by karel-3d** [comment]
I think you don't have enough memory in the VM
