### ISSUE TITLE
Trezor Bridge 2.0.25 crashes on Windows 7

### ISSUE THREAD

**Issue by bosomt** [trezor/trezord-go#119]
Trezor Bridge 2.0.25 crashes on Windows 7 after device goes to sleep.
Tested on two Win7 computers.

After sleep there is no trezord running.
There is no error or notice from Windows.
Works fine on Win10

**Comment by karel-3d** [comment]
does a device need to be connected? Does a web wallet need to be running? Or does it crash EVERY time?

**Comment by bosomt** [comment]
i'm not able to reproduce it at test W7 computer.
But it happened already on this computer too.
I will test and reply at home on personal computer

**Comment by karel-3d** [comment]
:( ok thanks

it's hard to catch these bugs that happen only sometimes :(((

**Comment by karel-3d** [comment]
I can replicate easily.

1) connect trezor to PC
2) wait for all the drivers etc to install
3) open wallet
4) sleep computer
5) disconnect trezor
6) wake up computer

bridge crashes

**Comment by karel-3d** [comment]
Fixed by c147d6d6c28c0fedb1ba52489aeb730a8fbe03a4
