### ISSUE TITLE
Detect different device on same USB path

### ISSUE THREAD

**Issue by matejcik** [trezor/trezord-go#121]
I want to keep a long-lived `TrezorClient` instance with reference to a particular Trezor device. I don't want to keep a session open, as that would prevent other clients from using the device.

Unless I constantly watch for changes, trezord won't notify me that a device has disconnected. That means that when the user unplugs a Trezor and plugs in a different one into the same port, my library will not be notified, because next call to `acquire -> post -> read -> release` will succeed. But possibly on a completely different device.

It would be nice to have a way to bind to a particular device.
One idea I had is to keep a monotonic counter of "device connections", and either make it part of the device path, or an optional argument to `acquire`. If the current device's ID doesn't match the one I'm sending, return an error.

Another way is to use USB serials instead of port paths.
Or some combination, or maybe something I didn't think of.

**Comment by karel-3d** [comment]
yeah listing USB serials instead of port paths is possible. It will add a USB call every enumeration, but that should be cheap.

There is problem with UDP though, that will keep using the ports, since the emulator does not give me the USB serial in any way

**Comment by karel-3d** [comment]
Should be fixed by this on libusb devices (>1.7.* on macos + windows, all versions on linux)

https://github.com/trezor/trezord-go/pull/122

solved by detecting different devices and increasing path.

Does not work on hidapi, wontfix as discussed off band
