### ISSUE TITLE
Link to downloads & gpg signatures

### ISSUE THREAD

**Issue by jonathancross** [trezor/trezord-go#132]
When using the wallet, users are prompted to update bridge if their version is old.
The [update page](https://wallet.trezor.io/#/bridge) links to the latest Bridge changelog, but not to the OpenPGP signature files.
I have filed a bug to link to the signatures: https://github.com/trezor/trezor-wallet/issues/286
But I think it would also be nice to link from here to the [compiled binaries & gpg signatures folder](https://wallet.trezor.io/data/bridge/latest/index.html).

Perhaps this can be done in the README or in the release notes?

**Comment by prusnak** [comment]
This is addressed by the new Bridge download dialog in the Suite: https://suite.trezor.io/web/bridge/ 

This now shows the link to the GPG binaries (for macOS and Windows, for Linux the GPG signatures are inside of the DEB/RPM files).
