### ISSUE TITLE
LIBUSB_ERROR_ACCESS on Archlinux

### ISSUE THREAD

**Issue by Nuc1eoN** [trezor/trezord-go#137]
I have installed the prebuild binary from AUR: https://aur.archlinux.org/packages/trezor-bridge-bin/
Getting this error upon opening https://wallet.trezor.io/#/:
```
 Action was interrupted
Error details: LIBUSB_ERROR_ACCESS
```

**Comment by prusnak** [comment]
Report the issue to AUR package maintainer.

**Comment by gabrielziegler3** [comment]
Installing [arch trezor udev tools build](https://aur.archlinux.org/packages/trezor-udev/) fixed here.
