### ISSUE TITLE
Change TREZOR Bridge status to Trezor Bridge status

### ISSUE THREAD

**Issue by bosomt** [trezor/trezord-go#140]
please change TREZOR to Trezor in 

https://github.com/trezor/trezord-go/blob/b4d138ec91666db81cc48766c275054a842025c2/server/status/windows.go

https://github.com/trezor/trezord-go/blob/1d0113f2b1c5f9ac32053b002e03c1cde769be17/README.md

https://github.com/trezor/trezord-go/blob/ceff3e0b7ab08381a9a9d37ff2aef467a9f3ab9c/server/status/template.go

**Comment by prusnak** [comment]
Fixed in https://github.com/trezor/trezord-go/commit/5ba012d03d42c9369205422df27c8b60878866d8
