### ISSUE TITLE
Allow Chromium-based browsers to use Trezor Bridge

### ISSUE THREAD

**Issue by whalehub** [trezor/trezord-go#141]
I'm currently using Vivaldi v2.3.1440.48 on my Windows 10 machine, which is a Chromium-based browser.

When I visit the Trezor wallet website, I receive the following message:

![2019-02-20 15 46 25 beta-wallet trezor io 56194d639263](https://user-images.githubusercontent.com/44198148/53099739-aed90b80-3526-11e9-9c5b-27dd77890880.png)

The detection appears to be based on the browser's user agent. When I use a Chrome extension to change my user agent to a default Chrome user agent, I can use the Trezor wallet website to manage my Trezor without any issues.

It would be great if you could add the user agents of Chromium-based browsers (Chromium, Opera, Vivaldi) to the list of supported browsers so that people who use one of these browsers don't have to fake their user agent just to manage their Trezor.

**Comment by prusnak** [comment]
We don't want to support untested browsers. So, feel free to fake your user agent and use the wallet, but then you at least know you are using untested environment and you know you should not contact our support.
