### ISSUE TITLE
Not sure if related

### ISSUE THREAD

**Issue by fwanky** [trezor/trezord-go#142]
Linux user, Is it normally to not be able to talk to things like Trezor Auth? I thought having the trezord-go would also allow me to use Trezor Auth but it doesn't seem to work for me, it just opens then instantly closes.

**Comment by prusnak** [comment]
What is Trezor Auth?

**Comment by fwanky** [comment]
@prusnak I'm not sure if you're familiar with something like a yubikey or 2Factor Authentication, but you can basically do the same with a trezor on windows, but i've tried it on linux and it doesn't seem to work.

Basically like logging into a service, password etc, then it will ask for you to connect your Trezor allowing you into said account.

**Comment by prusnak** [comment]
This is called U2F. You need to install udev rules for Trezor in Linux: https://raw.githubusercontent.com/trezor/trezor-common/master/udev/51-trezor.rules

These are usually installed automatically when you install the Bridge. But maybe you didn't install it from the package which contains these.
