### ISSUE TITLE
Android / aarch64 support

### ISSUE THREAD

**Issue by AlexanderPavlenko** [trezor/trezord-go#145]
Is it possible to run trezor bridge on Android device? If no, is it on a roadmap?

**Comment by prusnak** [comment]
It might be possible, but no one has tried that yet.

It is not on the roadmap, because on Android it is possible to use Trezor in Chrome natively (using WebUSB) - currently deployed to https://beta-wallet.trezor.io - just click on "Check new devices"

**Comment by karel-3d** [comment]
In addition: We use libusb, which calls low-level Linux APIs. I have no idea how does that work on Android.

There seem to be some Android support in libusb, but that would need additional testing, and maybe changes in the lowlevel libraries.

https://github.com/libusb/libusb/pull/242

**Comment by karel-3d** [comment]
Also read https://github.com/paritytech/parity-ethereum/issues/10058
