### ISSUE TITLE
unable to build

### ISSUE THREAD

**Issue by salfter** [trezor/trezord-go#15]
Here's what I'm running:

```
git clone https://github.com/trezor/trezord-go
cd trezord-go
git checkout f7b3ecd # v2.0.6
go build
```

Here's the output I'm getting:

```
trezord.go:10:2: cannot find package "github.com/trezor/trezord-go/server" in any of:
        /usr/lib64/go/src/github.com/trezor/trezord-go/server (from $GOROOT)
        /home/salfter/go/src/github.com/trezor/trezord-go/server (from $GOPATH)
trezord.go:11:2: cannot find package "github.com/trezor/trezord-go/usb" in any of:
        /usr/lib64/go/src/github.com/trezor/trezord-go/usb (from $GOROOT)
        /home/salfter/go/src/github.com/trezor/trezord-go/usb (from $GOPATH)
trezord.go:12:2: cannot find package "gopkg.in/natefinch/lumberjack.v2" in any of:
        /usr/lib64/go/src/gopkg.in/natefinch/lumberjack.v2 (from $GOROOT)
        /home/salfter/go/src/gopkg.in/natefinch/lumberjack.v2 (from $GOPATH)
```

I checked for submodules that might need to be checked out...there aren't any declared.  What am I missing?

**Comment by prusnak** [comment]
You need to clone into:


/home/salfter/go/src/github.com/trezor/trezord-go

**Comment by salfter** [comment]
Strangely enough, that worked.  Perhaps the build instructions could clarify that the source needs to be cloned into a stack of otherwise-empty nested directories.

With a bit of additional prodding, I was able to get a Gentoo ebuild working:

https://gitlab.com/salfter/portage/blob/master/net-p2p/trezord/trezord-2.0.6.ebuild

**Comment by prusnak** [comment]
I was puzzled at first too, but then I was told that it is very common requirement to clone sources into $GOHOME dir.

Anyways, we want people to use `xgo` way as it is more reproducible and thus easier to debug.
