### ISSUE TITLE
Trezor One Qubes 4.0 Error: device not found

### ISSUE THREAD

**Issue by Kixunil** [trezor/trezord-go#163]
**Problems**:

* trezord crashes when no Trezor is attached to VM
* Web wallet can't communicate with Trezor

**Trezor**: One, firmware initialized, wallet **not** initialized

**Environment**: Qubes 4.0 Debian 9 - based dispvm with Firefox 60.6.ESR, the [Trezor-QubesOS tutorial](https://wiki.trezor.io/Qubes_OS) **intentionally not** used to protect my privacy (hence dispvm).

I also didn't bother to install the Bridge to the base vm, because I wanted to try it out first. As far as my understand it shouldn't matter at all, but I mention it to be sure.

**Replication steps**

* Run dispvm
* `sudo apt-get install firefox-esr` (I used my trimmed-down version of Debian template, so I had to reinstall Firefox.)
* Download trezor bridge and install using `sudo dpkg -i FILENAME.deb`
* Refresh the page - bridge not detected
* `ps aux | grep trezor` shows nothing
* `/usr/bin/trezord` says: `error when initializing LibUSB.` with `Original error: LIBUSB_ERROR_OTHER`
* Attach Trezor to the VM
* after running `/usr/bin/trezord`, it starts and keeps running
* Refresh website
* `Action was interrupted Error details: device not found` message in the UI

Output from JS console:

```
[CoinInfo] Wait for coin info...
app.19660e8c68ddf7e115c8.js:8:24201
[app] User agent :  Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0
app.19660e8c68ddf7e115c8.js:46:335816
[app] build:  stable
app.19660e8c68ddf7e115c8.js:46:335816
[CoinInfo] Done reading coin; BTC
app.19660e8c68ddf7e115c8.js:46:335816
[CoinInfo] Current backend URL : https://btc1.trezor.io
app.19660e8c68ddf7e115c8.js:46:335816
[trezor.js] [device list] Initializing transports
app.19660e8c68ddf7e115c8.js:46:335816
[trezor.js] [device list] Configuring transports
app.19660e8c68ddf7e115c8.js:46:335816
[trezor.js] [device list] Configuring transports done
app.19660e8c68ddf7e115c8.js:46:335816
[trezor.js] [device list] Creating Device 
Object { path: "4", session: null, debugSession: null, product: 1, vendor: 21324, debug: false }
 undefined
app.19660e8c68ddf7e115c8.js:46:335816
[deviceList] Catched error, printing stack
app.19660e8c68ddf7e115c8.js:46:335816
Error: device not found
Stack trace:
e/<@https://wallet.trezor.io/app.19660e8c68ddf7e115c8.js:66:210594
w@https://wallet.trezor.io/app.19660e8c68ddf7e115c8.js:66:35481
b/o._invoke</<@https://wallet.trezor.io/app.19660e8c68ddf7e115c8.js:66:35271
S/</e[t]@https://wallet.trezor.io/app.19660e8c68ddf7e115c8.js:66:35657
r@https://wallet.trezor.io/app.19660e8c68ddf7e115c8.js:66:210795
r/<@https://wallet.trezor.io/app.19660e8c68ddf7e115c8.js:66:210893
a@https://wallet.trezor.io/app.19660e8c68ddf7e115c8.js:46:410066
D/<@https://wallet.trezor.io/app.19660e8c68ddf7e115c8.js:46:410211
c@https://wallet.trezor.io/app.19660e8c68ddf7e115c8.js:32:37251
app.19660e8c68ddf7e115c8.js:46:335816
e/<@https://wallet.trezor.io/app.19660e8c68ddf7e115c8.js:66:210594
w@https://wallet.trezor.io/app.19660e8c68ddf7e115c8.js:66:35481
b/o._invoke</<@https://wallet.trezor.io/app.19660e8c68ddf7e115c8.js:66:35271
S/</e[t]@https://wallet.trezor.io/app.19660e8c68ddf7e115c8.js:66:35657
r@https://wallet.trezor.io/app.19660e8c68ddf7e115c8.js:66:210795
r/<@https://wallet.trezor.io/app.19660e8c68ddf7e115c8.js:66:210893
a@https://wallet.trezor.io/app.19660e8c68ddf7e115c8.js:46:410066
D/<@https://wallet.trezor.io/app.19660e8c68ddf7e115c8.js:46:410211
c@https://wallet.trezor.io/app.19660e8c68ddf7e115c8.js:32:37251
app.19660e8c68ddf7e115c8.js:46:335816
[trezor.js] [device list] Cannot create device 
Error: device not found
Stack trace:
e/<@https://wallet.trezor.io/app.19660e8c68ddf7e115c8.js:66:210594
w@https://wallet.trezor.io/app.19660e8c68ddf7e115c8.js:66:35481
b/o._invoke</<@https://wallet.trezor.io/app.19660e8c68ddf7e115c8.js:66:35271
S/</e[t]@https://wallet.trezor.io/app.19660e8c68ddf7e115c8.js:66:35657
r@https://wallet.trezor.io/app.19660e8c68ddf7e115c8.js:66:210795
r/<@https://wallet.trezor.io/app.19660e8c68ddf7e115c8.js:66:210893
a@https://wallet.trezor.io/app.19660e8c68ddf7e115c8.js:46:410066
D/<@https://wallet.trezor.io/app.19660e8c68ddf7e115c8.js:46:410211
c@https://wallet.trezor.io/app.19660e8c68ddf7e115c8.js:32:37251
```

Trezord output:

```
2019/05/06 18:04:52 trezord is starting.
POST /
127.0.0.1 - - [06/May/2019:18:04:58 +0200] "POST / HTTP/1.1" 200 21
POST /enumerate
127.0.0.1 - - [06/May/2019:18:04:58 +0200] "POST /enumerate HTTP/1.1" 200 3
POST /listen
127.0.0.1 - - [06/May/2019:18:04:59 +0200] "POST /listen HTTP/1.1" 200 91
POST /listen
POST /acquire/1/null
127.0.0.1 - - [06/May/2019:18:05:06 +0200] "POST /acquire/1/null HTTP/1.1" 400 29
127.0.0.1 - - [06/May/2019:18:05:06 +0200] "POST /listen HTTP/1.1" 200 3
POST /listen
```

dmesg output

```
[ 7803.453088] vhci_hcd: vhci_device speed not set
[ 7803.655077] vhci_hcd: vhci_device speed not set
[ 7803.863051] vhci_hcd: vhci_device speed not set
[ 7804.071073] vhci_hcd: vhci_device speed not set
[ 7804.279057] vhci_hcd: vhci_device speed not set
[ 7804.279092] usb usb1-port1: Cannot enable. Maybe the USB cable is bad?
[ 7804.279123] usb usb1-port1: unable to enumerate USB device
```

However, USB cable is certainly OK as I used the same Trezor with same cable recently on another computer. I also tried completely different USB cable.

Other things I tried: reconnecting, reattaching the device several times using different combinations, restarting trezord, making sure the system is upgraded and has libusb installed, closing thunar, which obviously attempted to mess with USB device, running trezord as root (using sudo).

**Comment by prusnak** [comment]
Please follow the guide here: https://wiki.trezor.io/Qubes_OS

**Comment by Kixunil** [comment]
Thanks, I tried to see if the problem is in the hardware and it works. However, I'd like to protect my privacy from `sys-usb` which I consider less secure. Is there any way to bypass it?

**Comment by prusnak** [comment]
What exactly is the privacy problem with `sys-usb` here?

**Comment by Kixunil** [comment]
If it's compromised, it can spy on the communication.

**Comment by 4NobleTruths** [comment]
> Please follow the guide here: https://wiki.trezor.io/Qubes_OS

Thanks, finally got Trezor 1 to connect to AppVM this way, but the online trezor wallet still doesn't recognize it:
says "Transport error
Error details: WebUSB is not available on this browser." and prompts to download the bridge.

If i install the bridge in the appVM in addition to sys-usb, then the bridge doesn't start in the appVM, because it says something is already listening on that port:

>  03:21:47 localhost trezord[1272]: 2019/11/11 03:21:47 trezord v2.0.27 is starting.
Nov 11 03:21:47 localhost trezord[1272]: 2019/11/11 03:21:47 https: listen tcp 127.0.0.1:21325: bind: address already in use
Nov 11 03:21:47 localhost systemd[1]: trezord.service: Main process exited, code=exited, status=1/FAILURE
Nov 11 03:21:47 localhost systemd[1]: trezord.service: Unit entered failed state.
Nov 11 03:21:47 localhost systemd[1]: trezord.service: Failed with result 'exit-code'.

Then the browser just says the device is not connected.

Bitbox2 app connected to its device in the same qube without any issues at all.
Ledger NanoS had the usual similar Linux issues, but was able to resolve with the udev rules.

**Comment by 4NobleTruths** [comment]
Still get the Transport error in browser wallet. What else should I do?

trezord service starts in sys-usb

Rules in sys-usb are:
`
# Trezor
SUBSYSTEM=="usb", ATTR{idVendor}=="534c", ATTR{idProduct}=="0001", MODE="0660", GROUP="plugdev", TAG+="uaccess", TAG+="udev-acl", SYMLINK+="trezor%n"
KERNEL=="hidraw*", ATTRS{idVendor}=="534c", ATTRS{idProduct}=="0001", MODE="0660", GROUP="plugdev", TAG+="uaccess", TAG+="udev-acl"

# Trezor v2
SUBSYSTEM=="usb", ATTR{idVendor}=="1209", ATTR{idProduct}=="53c0", MODE="0660", GROUP="plugdev", TAG+="uaccess", TAG+="udev-acl", SYMLINK+="trezor%n"
SUBSYSTEM=="usb", ATTR{idVendor}=="1209", ATTR{idProduct}=="53c1", MODE="0660", GROUP="plugdev", TAG+="uaccess", TAG+="udev-acl", SYMLINK+="trezor%n"
KERNEL=="hidraw*", ATTRS{idVendor}=="1209", ATTRS{idProduct}=="53c1", MODE="0660", GROUP="plugdev", TAG+="uaccess", TAG+="udev-acl"

`
dmesg in appVM sees the device:
`
[Wed Jul 22 12:01:50 2020] vhci_hcd vhci_hcd.0: pdev(0) rhport(0) sockfd(0)
[Wed Jul 22 12:01:50 2020] vhci_hcd vhci_hcd.0: devid(131124) speed(2) speed_str(full-speed)
[Wed Jul 22 12:01:50 2020] vhci_hcd: vhci_device speed not set
[Wed Jul 22 12:01:50 2020] usb 1-1: new full-speed USB device number 4 using vhci_hcd
[Wed Jul 22 12:01:50 2020] vhci_hcd: vhci_device speed not set
[Wed Jul 22 12:01:50 2020] usb 1-1: SetAddress Request (4) to port 0
[Wed Jul 22 12:01:50 2020] usb 1-1: New USB device found, idVendor=1209, idProduct=53c1, bcdDevice= 1.00
[Wed Jul 22 12:01:50 2020] usb 1-1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[Wed Jul 22 12:01:50 2020] usb 1-1: Product: TREZOR
[Wed Jul 22 12:01:50 2020] usb 1-1: Manufacturer: SatoshiLabs
[Wed Jul 22 12:01:50 2020] usb 1-1: SerialNumber: XXXXXXXXXXXXXXXXXXXXXXX
[Wed Jul 22 12:01:50 2020] hid-generic 0003:1209:53C1.0003: hiddev96,hidraw0: USB HID v1.11 Device [SatoshiLabs TREZOR] on usb-vhci_hcd.0-1/input1
`

**Comment by prusnak** [comment]
Not sure what we can do here.
