### ISSUE TITLE
LIBUSB_ERROR_ACCESS

### ISSUE THREAD

**Issue by gretaneal** [trezor/trezord-go#166]
Hi there,

I built trezord-go binary, ran it and went to https://wallet.trezor.io in chromium (v70.0.3538.110).

I get error "Action was interrupted error details: LIBUSB_ERROR_ACCESS"

Same error with beta-wallet.

I ran it with -v and get the below (linked) every second in a loop

https://qbin.io/donald-trips-egav

Bus 001 Device 006: ID 1209:53c1 InterBiometrics SatoshiLabs TREZOR

iceweasel-uxp (based on firefox v52.9) doesn't recognise trezord is running when i navigate to wallet.trezor.io.

OS: GNU+Linux Hyperbola Milky Way

**Comment by prusnak** [comment]
Install udev rules: https://wiki.trezor.io/Udev_rules

**Comment by gretaneal** [comment]
Yeah I had already put the 51-trezor.rules file in /etc/udev/rules.d/ (sorry, should have mentioned that)

permissions are 644, owned by greta.

i just also put them in /usr/lib/udev/rules.d/ & /lib/udev/rules.d/ and ran

udevadm control --reload-rules && udevadm trigger

same issue though.

**Comment by prusnak** [comment]
It has to be owned by root with correct permissions. Otherwise udev won't load it

**Comment by gretaneal** [comment]
changed 51-trezor.rules to owned by root with 755 permissions (same as rules.d folder) and same issue.

i ran trezord-go with sudo and it works. Should I be running trezord-go with sudo?

**Comment by prusnak** [comment]
No. Trezor should not be needed. Anyway, if it works with sudo, there is no problem with the Bridge, but rather with your configuration. Try restarting maybe.

**Comment by gretaneal** [comment]
restarted and same issue >.<

thanks for the information & your help.

**Comment by shantee** [comment]
Same issue for me , And I pretty much did everything "gretaneal" did.

**Comment by rikhuijzer** [comment]
I could solve this issue on NixOS with `chromium` and `trezord-go` version 2.0.29 by starting the daemon with sudo privileges.

**Comment by sevanspowell** [comment]
I was able to solve this issue on NixOS with `firefox` and `chromium` by adding the following lines to my config:

```
  services.trezord.enable = true;
  services.udev.packages = [ pkgs.trezor-udev-rules ];
```

It seems, at least at this point in time, the trezord NixOS module does not automatically install the udev rules.

**Comment by prusnak** [comment]
> It seems, at least at this point in time, the trezord NixOS module does not automatically install the udev rules.

Well, it should:

https://github.com/NixOS/nixpkgs/blob/528a33727ff3db9712e79b21b6d120afb0e4221a/nixos/modules/services/hardware/trezord.nix#L47

Or is there a problem with the definition?

**Comment by sevanspowell** [comment]
Hmm no, you are correct. I'm not sure why it didn't work for me first-time.
