### ISSUE TITLE
MITM attack possibility?

### ISSUE THREAD

**Issue by maxogden** [trezor/trezord-go#168]
Hi, I was wondering if this attack vector was possible. Say I have an app that uses `http://localhost:21325` to talk to the bridge. Assuming the app process itself is sufficiently sandboxed, could some malware (say a shady VPN client) MITM the unencrypted TCP session and modify the payloads sent to the bridge, and hope the user confirms on the device without noticing?

**Comment by prusnak** [comment]
This is not a bridge issue. The same malware can MITM the USB connection for example.

At all times the user HAS to check the values shown on the device display and not confirm something that is not right.
