### ISSUE TITLE
Trezor-Bridge-2.0.6amd64.deb update, Wallet not responding

### ISSUE THREAD

**Issue by elrippo** [trezor/trezord-go#17]
Dear all,
i am running Kubuntu 14.04 on 3.13.0-141-generic #190-Ubuntu SMP Fri Jan 19 12:52:38 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

After updating the new bridge from 1.2.1 to 2.0.6, wallet was not responding, restart did not help. "aptitude purge trezor-bridge" or "aptitude reinstall trezor-bridge" did not work.

Via dpkg just brought another failure -->
"sudo dpkg --purge --force-all trezor-bridge
dpkg: Warnung: Problem wird übergangen, weil --force angegeben ist: 
dpkg: Warnung: Paket ist in einem sehr schlechten inkonsistenten Zustand - Sie sollten
es erneut installieren, bevor Sie es zu entfernen versuchen.
(Lese Datenbank ... 320850 Dateien und Verzeichnisse sind derzeit installiert.)
Entfernen von trezor-bridge (2.0.6) ...
/var/lib/dpkg/info/trezor-bridge.prerm: 1: /var/lib/dpkg/info/trezor-bridge.prerm: systemctl: not found
/var/lib/dpkg/info/trezor-bridge.prerm: 2: /var/lib/dpkg/info/trezor-bridge.prerm: systemctl: not found
dpkg: Fehler beim Bearbeiten des Paketes trezor-bridge (--purge):
Unterprozess installiertes pre-removal-Skript gab den Fehlerwert 127 zurück
/var/lib/dpkg/info/trezor-bridge.postinst: 1: /var/lib/dpkg/info/trezor-bridge.postinst: systemctl: not found
/var/lib/dpkg/info/trezor-bridge.postinst: 2: /var/lib/dpkg/info/trezor-bridge.postinst: systemctl: not found
dpkg: Fehler beim Aufräumen:
Unterprozess installiertes post-installation-Skript gab den Fehlerwert 127 zurück
Fehler traten auf beim Bearbeiten von:
trezor-bridge
"

The only thing that helped was to remove the scripts in down below, then i could purge the trezor-bridge package.
/var/lib/dpkg/info/trezor-bridge.postinst
/var/lib/dpkg/info/trezor-bridge.preinst
/var/lib/dpkg/info/trezor-bridge.prerm

After that, installing trezor-bridge-1.2.1-amd64.deb brought back a working wallet.
Please look into it, the new bridge is not working on this system.

Kind regards,
elrippo

**Comment by prusnak** [comment]
Sorry, we officialy support only distributions with systemd as its init system. You are using very old distro. Update to newer version of Ubuntu (e.g 16.04 if you want to stay at Ubuntu LTS) or Debian 9.

Another option is extracting the binary from deb package (using `dpkg -x`) and running trezord manually.
