### ISSUE TITLE
Display freezes if I lock the computer screen while some user action is required on device

### ISSUE THREAD

**Issue by pankrats** [trezor/trezord-go#170]
Chrome, Linux
wallet.trezor.io

The original issue was "Device freezes when displaying Bitcoin Cash Receiving address if I lock the computer screen". 

How to reproduce: 
1. Switch to Bitcoin Cash
2. Go to Receive tab 
3. Click on Show full address, wait for the address to appear on Trezor Screen
4. Lock your computer (for 1 min approx)
5. Restore your computer. 

Result: the screen becomes irresponsive. 

![screen](https://user-images.githubusercontent.com/31442634/46805460-62561600-cd65-11e8-9621-ad0d055820c8.gif)

Update: 

The error does not occur with WebUSB, so it looks like a Bridge issue. 

The issue is unrelated to Bitcoin Cash, it happens basically any time if you lock your computer for 1 minute while a user action is required on device.

**Comment by pankrats** [comment]
Indeed, seems like a Bridge issue. I have found another case:

![2019-06-25 18 07 05](https://user-images.githubusercontent.com/31442634/60114407-107ae200-9774-11e9-8e45-afe35f31b86d.jpg)

Steps to reproduce: 
1) Lock your computer for 1 minute, when some user action is required on device 
2) Unlock your computer, tap any button on the device.
Result: the display freezes. 

If you reload wallet page after the device screen becomes responsive again.

**Comment by bosomt** [comment]
tested with bridge 2.0.27 + FW 2.2.0 = bug is still presnet

**Comment by prusnak** [comment]
I think this should be fixed with bridge 2.0.30, can you please retest @bosomt ?

**Comment by bosomt** [comment]
**QA OK**

Wallet commit c436bacae06bb4a2dd42af37edb7861b41f66b35
device model T fw 2.3.4
Bridge version 2.0.30
Mint Linux

**Comment by bosomt** [comment]
@prusnak please close, i dont have rights to close issues in this repository

**Comment by prusnak** [comment]
Thanks for testing!
