### ISSUE TITLE
Unable to install Trezor Bridge on Kali..

### ISSUE THREAD

**Issue by SkyDiver069** [trezor/trezord-go#172]
Installation worked fine on Fedora 25 and I was able to configure the device.  Problem for me is that Kali is my main OS.

4.19.0-kali5-amd64 #1 SMP Debian 4.19.37-6kali1 (2019-07-22) x86_64 GNU/Linux

Example:
root@UpdateService:/media/pmathieu/4272-234D/Trezor# ls
trezor-bridge_2.0.27_amd64.deb  trezor-bridge_2.0.27_i386.deb
root@UpdateService:/media/pmathieu/4272-234D/Trezor# aptitude install trezor-bridge_2.0.27_i386.deb
Couldn't find any package whose name or description matched "trezor-bridge_2.0.27_i386.deb"
Unable to apply some actions, aborting
root@UpdateService:/media/pmathieu/4272-234D/Trezor# 

Installation attempts with both apt and aptitude produced the same results.  Ideas?

**Comment by prusnak** [comment]
That's not how you install a deb. It's `dpkg -i` afaik.
