### ISSUE TITLE
Decrease the waiting time for emulator

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezord-go#174]
Currently, when you run trezord with support for emulator (e.g. `trezord-go -e 21324`) and the emulator is **not** running the user is experiencing lags (~5s per device discovery) because trezord is waiting for the emulator. This makes it somewhat unusable to use it permanently - in other words, the goal is to have trezord-go running in the background which supports both devices and emulators right out of the box.

I believe the concerned line is:
https://github.com/trezor/trezord-go/blob/1ff6715175ef4add89052cd6d7d181b1a5d7af5a/usb/udp.go#L23

@prusnak @karel-3d do you see any reasons not to decrease this value to 1s for example? Is it too low?

**Comment by prusnak** [comment]
By digging in the git history I found out that the last value of 700ms was not enough for Trezor One(!) emulator on macOS. I'd say let's decrease this to 500ms and test if this is still the case on macOS.

**Comment by tsusanka** [comment]
Great. Will do a branch and test on Szymon's mac

**Comment by tsusanka** [comment]
Since Szymon had some difficulties on MacOS we have agreed to do an `if` branch and use 5000 for Mac and 700 elsewhere. We need to test this change properly including Windows.

**Comment by tsusanka** [comment]
Merged via 55e66adbdb5791175c13a015028cd8ca4cf8fbc5
