### ISSUE TITLE
Verbose logging by default on windows

### ISSUE THREAD

**Issue by daniel5gh** [trezor/trezord-go#178]
On windows the the link `c:\ProgramData\Microsoft\Windows\Start Menu\Programs\StartUp\TREZOR Bridge.lnk` includes `-v` on its command line:

`"C:\Program Files (x86)\TREZOR Bridge\trezord.exe" -v -l "%APPDATA%\TREZOR Bridge\trezord.log"`

This leads to excessive logging, 20MB rotate every roughly 4 minutes. Regular end users won't need this level of logging by default. SSDs are pretty good nowadays, but some would argue this leads to unnecessary wear and tear.

**Comment by Nessa-G22** [comment]
[Connect 22](github) 

> `22`

**Comment by Nessa-G22** [comment]
Hello

**Comment by Nessa-G22** [comment]
Connect 32

**Comment by Nessa-G22** [comment]
@Nessa-G22

**Comment by Nessa-G22** [comment]
@Nessa-G22

**Comment by Nessa-G22** [comment]
GitHub @Nessa-G22

**Comment by bosomt** [comment]
I can confirm that even with latest  build log in Windows 10 is almost 1000x bigger than in Linux even there was no device connected and it's running for less than minute

**Comment by bosomt** [comment]
same behavior with 2.0.30 RC2
Windows 10MB+
KUbuntu less than 500kB

**Comment by prusnak** [comment]
Fixed in 90a0eefd08927f712e6cb4ae6133a2dbd47e1223
