### ISSUE TITLE
Passphrase-file argument not working functionally

### ISSUE THREAD

**Issue by Sezerb** [trezor/trezord-go#179]
**dpkg-sig**
When the command below is executed, signing operation fails.
dpkg-sig -k "keyId" --passphrase-file "passphraseFile" --sign builder foo.deb

Processing foo.deb...
gpg: Fatal: passphrase-fd is invalid: Bad file descriptor
E: Signing failed. Error code: 512

Is this a known issue, or am I missing something?

**Comment by prusnak** [comment]
This is a generic `dpkg-sig` question in no way related to trezord-go. I don't see any problem with this except for the fact that man page for dpkg-sig says you should not use this as it is insecure.
