### ISSUE TITLE
2.0.30 RC1 says LIBUSB_ERROR_ACCESS

### ISSUE THREAD

**Issue by bosomt** [trezor/trezord-go#192]
2.0.30 RC1 says LIBUSB_ERROR_ACCESS

Tested in :

latest Mint Linux: Chromium and Firefox
latest Fedora Linux: Firefox

attaching log

[log.gz](https://github.com/trezor/trezord-go/files/4621680/log.gz)

**Comment by bosomt** [comment]
and I experienced that I need ed to restart trezord process after i tried to send transaction or confirm address.

Process was running but http://127.0.0.1:21325/ was dead

**Comment by bosomt** [comment]
windows 10 version stops responding after few minutes,
attached logs from fresh installation 69MB 

[TREZOR Bridge win10.zip](https://github.com/trezor/trezord-go/files/4626905/TREZOR.Bridge.win10.zip)

**Comment by prusnak** [comment]
@tsusanka I just had an idea of updating bundled libusb to latest version (1.0.21->1.0.23). This is done in the `libusb-update` branch. We might be hitting an issue that's been resolved in the libusb upstream. Let's try the bridge from this branch to see whether the issue magically resolves itself via the update.

**Comment by tsusanka** [comment]
Oh good idea! The branch [fails](https://travis-ci.org/github/trezor/trezord-go/builds/710789900) however for mac and win build. I guess you have a better idea what went wrong so I won't debug it now. Let me know if I should.

**Comment by prusnak** [comment]
I managed to fix the build failures for Mac+Win builds in the `libusb-update` branch. Here is the latest output from Travis: https://travis-ci.org/github/trezor/trezord-go/builds/711423430

**Comment by tsusanka** [comment]
I have passed on the builds to QA.

**Comment by tsusanka** [comment]
QA no longer reports this!! 🎉🎉

**Comment by bosomt** [comment]
@tsusanka happy to do that !
