### ISSUE TITLE
MacOS release candidate installation fails

### ISSUE THREAD

**Issue by sorooris** [trezor/trezord-go#194]
**Describe the bug**
Installing the Bridge 2.0.30 RC3 ends in an error.

**App version and revision**
Bridge 2.0.30 RC3 (bff32065)

**Setup:**
 - OS: MacOS Catalina 10.15.6

**To Reproduce**
1. Start the install wizard
2. Navigate through the steps
3. See error

**Expected behavior**
Installation ends successfully.

**Screenshots**
N/A

**Additional context**
The machine has developers apps allowed.

**Comment by tsusanka** [comment]
What error it prints? Or it crashes?

**Comment by tsusanka** [comment]
Might be related to https://github.com/trezor/trezord-go/commit/4e5a0d35e42b316bee0a854bc965805838b9ab71

**Comment by prusnak** [comment]
> Might be related to [4e5a0d3](https://github.com/trezor/trezord-go/commit/4e5a0d35e42b316bee0a854bc965805838b9ab71)

@tsusanka Can you try reverting the commit whether this helps?

**Comment by sorooris** [comment]
@tsusanka Nothing specific:
> The installation failed.
> The installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.
![image](https://user-images.githubusercontent.com/10185314/91046591-01621f00-e619-11ea-98a3-99e9cb2ba289.png)

Attempt at closing the window with the X button displays a dialog with an _Show error_ option; however selecting it does not trigger any apparent action.
![image](https://user-images.githubusercontent.com/10185314/91046914-8c431980-e619-11ea-96f2-f8e5a9af87d6.png)

**Comment by tsusanka** [comment]
Sent via Asana, GH doesn't allow .pkg files.

**Comment by sorooris** [comment]
@tsusanka Tested the 8a597a revision, reported in Asana; however I've encountered a similar issue to #186 - details are in the [comment there](https://github.com/trezor/trezord-go/issues/186#issuecomment-679379335).

**Comment by tsusanka** [comment]
@prusnak how do we want to approach this? Should I revert the commit in master or do you want to try nixifying this? :)

**Comment by prusnak** [comment]
If the revert fixes the installation, let's do it.
