### ISSUE TITLE
Re-Investigate macOS signing/notarization

### ISSUE THREAD

**Issue by prusnak** [trezor/trezord-go#204]
We have some reports the new 2.0.30 is not properly signed, although we used the method we've always used using the fresh keys issued by Apple.

Let's investigate whether these are valid. And/ or whether we should use notarization instead of signing locally.

**Comment by bosomt** [comment]
@prusnak 2.0.30 is not signed in Windows version too.
2.0.27 was signed, do you want me to send separate issue ?

**Comment by prusnak** [comment]
I can see the 2.0.30 is signed

**Comment by bosomt** [comment]
@prusnak i see it's signed but there is some kind of error, i will send it soon

**Comment by kklash** [comment]
This is what a user sees when they try to install trezor-bridge on Big Sur: 

<img width="330" alt="Screen Shot 2020-11-23 at 8 48 25 AM" src="https://user-images.githubusercontent.com/31221309/99991300-b36ccc80-2d69-11eb-9a11-266b7b6b5933.png">

Haven't tested other Mac OS versions.

**Comment by igor-hnizdo** [comment]
Is fixed by  https://github.com/trezor/trezord-go/pull/259
