### ISSUE TITLE
Bridge 2.0.30 installer binary not properly signed in Windows 10

### ISSUE THREAD

**Issue by bosomt** [trezor/trezord-go#205]
Downloaded via link from Suite.

**Environment**
OS: Microsoft Windows [Version 10.0.19042.572]
Suite commit 36c7716bd5c2a01de4b8981a2ac680f80c79164c

**Screenshots**
![image](https://user-images.githubusercontent.com/31506317/98842182-7a6b5880-2449-11eb-9564-69c9dab84cd6.png)
![image](https://user-images.githubusercontent.com/31506317/98842389-cd451000-2449-11eb-9522-4d7b46993856.png)

**Comment by prusnak** [comment]
This should be fixed in the re-published binary at https://data.trezor.io/bridge/2.0.30/trezor-bridge-2.0.30-win32-install.exe

Can you please try again?

**Comment by bosomt** [comment]
**QA OK**

`Microsoft Windows [Version 10.0.19042.630]`

![image](https://user-images.githubusercontent.com/31506317/98908263-71699e00-24c0-11eb-9c54-9425bd996a65.png)
