### ISSUE TITLE
Incorrect "You were disconnect." error

### ISSUE THREAD

**Issue by alexdupre** [trezor/trezord-go#207]
Since a few trezord/wallet releases I constantly see the following error when running on FreeBSD:

![Screenshot_20201112_100703](https://user-images.githubusercontent.com/3694371/98919614-52263d00-24cf-11eb-8d44-22746287ee4e.png)

But the the device is not disconnected and it works perfectly, so it seems the error is appearing even if it shouldn't. What triggers it?

**Comment by prusnak** [comment]
Sorry, FreeBSD is not support. You are encouraged to investigate the issue and send a pull request.

**Comment by alexdupre** [comment]
It's what I'm going to do, but if you could tell me what's the condition that triggers that error it might speed up finding the issue.

**Comment by alexdupre** [comment]
Ok, I think it uses the browser `navigator.Online` property, that for some reason is set to `false` on my chromium (I see many bug reports on that). With firefox it's set to `true` and in fact the error is not present.
