### ISSUE TITLE
What's the reason for trezor.io offering 2.0.27 as the latest version instead of 2.0.30?

### ISSUE THREAD

**Issue by c0deright** [trezor/trezord-go#208]
Hi,

$title says it all. https://wallet.trezor.io/#/bridge is offering v2.0.27 of trezor-bridge but v2.0.27 was released May of 2019. The most recent release is v2.0.30.

So what's up with the releases after v2.0.27? Why aren't they offered for download on the official trezor.io website?

**Comment by prusnak** [comment]
We'll deploy 2.0.30 tomorrow to wallet.trezor.io

There were significant changes and we wanted to test them first

**Comment by c0deright** [comment]
In the meantime, I saw that you offer 2.0.30 on https://beta-wallet.trezor.io. Was just a bit confused because releases on github weren't marked "beta".

Thanks for your reply!

**Comment by saurik** [comment]
@prusnak https://suite.trezor.io/web/bridge/ is also only offering 2.0.27 (which I noticed as I have 2.0.30 installed)

**Comment by saurik** [comment]
FWIW, a year and a half later, and, despite updating "Trezor Suite (desktop)", I am somehow still only running 2.0.30 (not the aforementioned 2.0.31)? If I go to the web page to update the bridge, it still only tells me 2.0.27 is the latest version... however, the changelog now goes up to 2.0.33. What is the official distribution path for the past over four years of development on this software?

**Comment by prusnak** [comment]
@tsusanka can you please comment on the version situation?
