### ISSUE TITLE
Trezor One: FW upgrade not possible after bridge upgrade

### ISSUE THREAD

**Issue by Kommissar-Kugelblitz** [trezor/trezord-go#209]
Trezor One
I upgraded the bridge version from 2.0.27 to 2.0.30. Afterwards it was not possible to upgrade the FW of my Trezor One. Pressing both hardware buttons and then connecting resulted in stuck in the bootloader screen. Google Chrome noticed that I connected the Trezor but the Chrome Website did not recognize. Screen on the Trezor showed Bootloader and 1.8.0 and nothing happens for minutes.

My manual workaround: Downgraded the bridge back to 2.0.27 and then FW upgrade worked like a charm.
(Bootloader version 1.8.0)
I don't remember the FW version of the Trezor One Model. But shouldn't be too old, as my last update is not older than 6 months.

**Comment by prusnak** [comment]
Which OS was that?

**Comment by Kommissar-Kugelblitz** [comment]
Windows 7

**Comment by sorooris** [comment]
@prusnak Confirming issue, details in issue #210

**Comment by prusnak** [comment]
Fixed in https://github.com/trezor/trezord-go/commit/5438e38dd37f8865e2ad27840480c7f81c1edfff + https://github.com/trezor/trezord-go/commit/bcdcefcba28d8cccd45fe3e9d1cfb0f172071025
