### ISSUE TITLE
Windows: Device in bootloader mode not detected

### ISSUE THREAD

**Issue by sorooris** [trezor/trezord-go#210]
**Describe the bug:**
Device is detected as long as it is in the normal mode, reconnecting it in bootloader mode renders it undetectable by Bridge 2.0.30 - does not occur with 2.0.29 and older. 

**App version and revision:**
Bridge 2.0.30 public

**Setup**:
OS: Windows 10.0.19041.572
Browser: Firefox 82.0, 83.0; Chrome 86.0.4240.111, 87.0.4280.66
Device: any firmware (tested model T 2.3.1, 2.3.4; T1 1.8.3, 2.3.1)

**Steps to reproduce:**
Prerequisite - Bridge 2.0.30 installed
1. Navigate to Suite/MyTrezor wallet,
2. Reconnect device in bootloader mode.

**Expected behavior:**
Device is detected when in bootloader mode.

**Actual behavior:**
0 connected devices displayed in 127.0.0.1:21325 and both Suite and MyTrezor Wallet connect device prompt/modal displayed.

**Screenshot:**
N/A

**Comment by prusnak** [comment]
Is it just Windows or macOS/Linux as well?

**Comment by bosomt** [comment]
KUbuntu works fine, i was able ton install firmware in bootloader mode, both browsers and bridge see devices

**QA OK**

KUbuntu 20.03
Chrome 86 + Firefox 82.0.3
Trezor Bridge 2.0.30 /fresh install/
T1 + TT


![image](https://user-images.githubusercontent.com/31506317/99945532-10ba4b00-2d75-11eb-8c38-e30524077d59.png)

**Comment by sorooris** [comment]
@prusnak macOS **QA OK**

**Setup:**
OS: macOS Big Sur 11.0.1
Browsers:
- Firefox 77.0.1 - **OK**
- Firefox 83.0 - **OK**
- Chrome 87.0.4280.67  **OK**

**Comment by bosomt** [comment]
**QA NOK**

Connected devices 0 

Windows 10.0.19042.630
Chromium and Firefox, current versions
Fresh install of 2.0.30
T1 + TT in BL mode

**Comment by tsusanka** [comment]
>  OS: Windows 20.0.19041.572

@sorooris you mean Windows 10 right?

**Comment by tsusanka** [comment]
@wendys-cats could you please retest this on your Win 10?

**Comment by sorooris** [comment]
@tsusanka sorry :man_facepalming:  yes of course

> > OS: Windows 20.0.19041.572
> 
> @sorooris you mean Windows 10 not 20 right?

**Comment by wendys-cats** [comment]
**QA NOK**

OS Windows 10 home

devices (tested TT 2.3.4 and T1 1.9.3)

**Chrome** Version 87.0.4280.66 (Official Build) (64-bit) NOK???
Chrome itself DID detect device in bootloader mode - a chrome pop up notification showed up and upon clicking, redirected the user to trezor.io web. But neither Suite nor Wallet detected device in bootloader mode.

**Chrome** Version 86 NOK

**Firefox** 83.0 NOK

**Comment by tsusanka** [comment]
Detailed logs from my testing Windows. All from a fresh install of trezord.

- 2.0.30 with Trezor connected in a normal way: [30-normal.txt](https://github.com/trezor/trezord-go/files/5604562/30-normal.txt)
- 2.0.30 with Trezor connected in a bootloader (not recognized here): [30-bootloader.txt](https://github.com/trezor/trezord-go/files/5604561/30-bootloader.txt)
- 2.0.27 with Trezor connected in a normal way: [27-normal.txt](https://github.com/trezor/trezord-go/files/5604559/27-normal.txt)
- 2.0.30 with Trezor connected in a bootloader: [27-bootloader.txt](https://github.com/trezor/trezord-go/files/5604558/27-bootloader.txt)

**Comment by tsusanka** [comment]
There is a new version of [hidapi 0.10.1](https://github.com/libusb/hidapi/releases/tag/hidapi-0.10.1). I guess we can try to upgrade even though the release notes do not mention anything related

**Comment by tsusanka** [comment]
Ad libusb: I am wondering if this [commit](c3deb6dd6440fd467ce12965742f2d7a228b3bbe) could help by any chance. I will try to upgrade both.

**Comment by prusnak** [comment]
@tsusanka Okay, I'll update both libusb and hidapi in master and we can try that out

**Comment by prusnak** [comment]
Fixed in https://github.com/trezor/trezord-go/commit/5438e38dd37f8865e2ad27840480c7f81c1edfff + https://github.com/trezor/trezord-go/commit/bcdcefcba28d8cccd45fe3e9d1cfb0f172071025

Signed binaries for testing will be available soon(tm)
