### ISSUE TITLE
Trezor Bridge not working with Tor Browser on Tails OS

### ISSUE THREAD

**Issue by jingxi285** [trezor/trezord-go#214]
Tested latest Trezor Bridge on latest Tails OS 4.14 but it gives an error in Tor Browser.
Could support be added for Tails OS? It uses the Tor Browser, which is based on Firefox.  Just visit wallet.trezor.io
Adblock is disabled, so it should work fine....

**Comment by prusnak** [comment]
You need to enable Trezor Bridge in the Tor Browser: https://wiki.trezor.io/Tor

**Comment by jingxi285** [comment]
Hello Sir. thank you for the tip. I followed the guide, carefully read few times, and restarted Tor Browser, but same problems.

May I ask, is latest Tails working ok for you with Trezor?

All Tor Browsing is working well, apart from Trezor.

Just tried, same issue "Transport error" "Error details: WebUSB is not available on this browser".

Restarted, same error, it says Trezor Bridge is "Not installed"

BTW, isn't steps (4) and (5) risky?
better to keep referrer hiden.
**_Search for the key network.http.referer.hideOnionSource
Set the value to false_**

**Comment by prusnak** [comment]
> better to keep referrer hiden.

Bridge needs to see the Origin so it enables Trezor only on selected sites, not all of them.

If you have followed the guide on Wiki and it does not work, please contact our support - https://trezor.io/support/technical/issue/ - Github is not a support platform.

Thank you!

**Comment by jingxi285** [comment]
> > better to keep referrer hiden.
> 
> Bridge needs to see the Origin so it enables Trezor only on selected sites, not all of them.
> 
> If you have followed the guide on Wiki and it does not work, please contact our support - https://trezor.io/support/technical/issue/ - Github is not a support platform.
> 
> Thank you!

Okay I see. Yes I have written to them, but no reply yet.

**Comment by jingxi285** [comment]
Pavol, Nearly a month has passed.
Feels like no developer at Trezor/SatoshiLabs is to be working on making Trezor compatible with Tails OS.
Can any developer be assigned?
Sorry I've not got time to test or develop the support myself.

**Comment by prusnak** [comment]
Have you followed the guide I gave you? (including steps 4 and 5?)

**Comment by jingxi285** [comment]
> Have you followed the guide I gave you? (including steps 4 and 5?) Otherwise this will not work.

Yes I followed the guide, as I clearly wrote 24 days ago, please scroll up this page.

prusnak directed me to a support mailbox without any developers. That support mailbox just closed my tickets automatically today, no one addressed the issues.

> Btw, Trezor works out of the box in Tails OS with Electrum and we put effort to have this seamless experience.

I can confirm that Trezor **does not work out of the box with Tails OS tails-amd64-4.14-img**, as I wrote 24 days ago. Including steps 4 and 5.

**Comment by prusnak** [comment]
Please post a screenshot of what you see when you visit the following URL in the  Tor Browser: http://127.0.0.1:21325

**Comment by jingxi285** [comment]
> Please post a screenshot of what you see when you visit the following URL in the Tor Browser: http://127.0.0.1:21325

Please post a screenshot to show that it Tails OS is really working. Sorry you've ignored this fault for 24 days, I'll need to see some proof before I waste further time debugging your bugs! Thanks
