### ISSUE TITLE
Trezor Bridge "failed to install" on a new rapsberry pi 400

### ISSUE THREAD

**Issue by xwing22** [trezor/trezord-go#215]
"One of the selected package failed to install correclty. More information is available in the detailed report."

Where can I at least find the detailed report on a rapsberry OS? I used the pi user to execute the install package

I tried installing udev rules as described here :
https://wiki.trezor.io/Udev_rules

but it didn't fix anything.

Also tried the 30 version as the one on the trezor site is 27 but same results.. Help would be very appreciate to set up the bridge as it is required for what I want to do.

thanks

**Comment by prusnak** [comment]
If you have 64-bit version of Raspberry Pi OS you can use this package: 

https://data.trezor.io/bridge/2.0.30/trezor-bridge_2.0.30_arm64.deb

32-bit version is not supported

**Comment by xwing22** [comment]
still the same problem:

my processorL
roadcom BCM2711 quad-core Cortex-A72
(ARM v8) 64-bit SoC @ 1.8GHz

![2021-01-06-121102_1920x1080_scrot](https://user-images.githubusercontent.com/52837583/103824705-896d2200-5018-11eb-9de3-42ca4c2552e5.png)

**Comment by prusnak** [comment]
Run this in the terminal to see if you are running 64-bit system (should contain `aarch64` string, not `armv7l`):

```
uname -a
```

If you are on 64-bit, run the following commands:

```
wget https://data.trezor.io/bridge/2.0.30/trezor-bridge_2.0.30_arm64.deb
sudo dpkg -i trezor-bridge_2.0.30_arm64.deb
```

**Comment by xwing22** [comment]
Linux raspberrypi 5.4.79-v7l+ #1373 SMP Mon Nov 23 13:27:40 GMT 2020 armv7l GNU/Linux


so I guess I can't make it work then on this  rapsberry. 

Thanks for your help

**Comment by prusnak** [comment]
> so I guess I can't make it work then on this rapsberry.

Correct. You need to install 64-bit version of Raspberry Pi OS
