### ISSUE TITLE
Is Trezor Bridge mandatory to have Trezor detected in a web browser?

### ISSUE THREAD

**Issue by kucharskim** [trezor/trezord-go#217]
I'm on https://wallet.trezor.io/#/ and page says:

- Connect Trezor and Check for devices

later down the page it's written:

- Device not recognized? Try installing the Trezor Bridge.

I didn't install Trezor Bridge, but I'm not sure should I. Vocabulary used in above sentence is not clear is Trezor Bridge essential to use Trezor hardware wallet in web browser or is it optional and I need to configure my operating system to expose Trezor to a web browser.

**Comment by kucharskim** [comment]
Chrome doesn't say anything, but Firefox actually gives error message:

> Error details: WebUSB is not available on this browser.

**Comment by prusnak** [comment]
If you use Chrome just press the `+ Find Device` button. For Firefox you need to use the Bridge.

The best option is to use the new Trezor Suite - https://suite.trezor.io - no bridge installation is needed for that one either.

**Comment by kucharskim** [comment]
I did click on `Find Device` and in Chrome nothing happens, that's why it's not clear to me. I've opened this GitHub issue not to ask for help, but ask for clarification in the documentation what is needed exactly with what browser to use Trezor.

**Comment by kucharskim** [comment]
If README could explain why Trezor Bridge is needed any in what circumstances.

**Comment by prusnak** [comment]
> I did click on `Find Device` and in Chrome nothing happens

The dialog window should appear. You might have a non-working USB cable, try another one. 

> If README could explain why Trezor Bridge is needed any in what circumstances.

You need Bridge for Firefox, you don't need Bridge for Chrome

**Comment by kucharskim** [comment]
I think you are jumping into conclusions way too fast. I know I don't have a loose cable. I'm using OpenBSD and I'm trying to understand technical components needed to make Trezor work.

**Comment by prusnak** [comment]
OK, check my answers in https://github.com/trezor/trezord-go/issues/218
