### ISSUE TITLE
trezor bridge not recognized

### ISSUE THREAD

**Issue by xyz0o** [trezor/trezord-go#222]
I am new to Trezor one wallet and setting it up. I have tried installing trezor bridge from its official trezor.io webpage, although installed, when refreshing the page, it doesn't recognize it. I first tried it on win 10 then read that win 10 has problem with this tool, now am trying it on linux mint, still no success. Have tried firefox, Brave and chrome browsers too. what should I do?

**Comment by prusnak** [comment]
Try different USB cable or different USB port.

**Comment by xyz0o** [comment]
> Try different USB cable or different USB port.

the cable originally came with the device, why would some one sell something that doesn't work!! also when I plug it in, the device itself turns on and the trezor page can recognize and pair with it, so I would say it's not the cable.

**Comment by prusnak** [comment]
You say the Trezor page can recognize and pair with the device, so what exactly is the problem here? 

Please provide screenshot of the problem

**Comment by xyz0o** [comment]
sorry, maybe I didn't explain well. when I click on the "check for devices" there is "Trezor" and I click connect and it says paired (for some reason I cannot take the screenshot of that pop up window).
![Screenshot from 2021-02-27 16-28-17](https://user-images.githubusercontent.com/77616805/109390242-5bb1a480-7908-11eb-9b4f-54b506b398d4.jpg)
but then when I click on the "trezor bridge" down the page, it doesn't recognize the bridge is already installed
![Screenshot from 2021-02-27 16-35-33](https://user-images.githubusercontent.com/77616805/109390509-f5c61c80-7909-11eb-9402-f75153e8b5e8.jpg)

**Comment by prusnak** [comment]
If you click "Check for devices" - this will use WebUSB available in Chrome and no bridge is needed in that case, so it might be still possible the bridge is not running.

What system/version do you use? Does it use systemd?

**Comment by xyz0o** [comment]
I think I got it worked now! I was using Brave browser, now I changed to chrome and it worked.
