### ISSUE TITLE
Increasing memory usage?

### ISSUE THREAD

**Issue by slowbackspace** [trezor/trezord-go#223]
Bridge Version: 2.0.27 (downloaded and installed separately, running as `/Applications/Utilities/TREZOR Bridge/trezord -l /Users/maros/Library/Logs/trezord.log` )
OS: MacOS 11.2.2

I am not sure if it is legit, but activity monitor in macOS shows increasing memory usage of trezord process. It is not a first time I noticed it, but I can't give you ani specific steps to reproduce as I don't even know for how long is trezord running on my system.

Reported memory usage by activity monitor went from 180MB to 320MB in 20 hours.

<img width="807" alt="Screenshot 2021-03-04 at 10 08 25" src="https://user-images.githubusercontent.com/6961901/109939660-92553980-7cd1-11eb-985e-99fc135fcbb6.png">

[log.gz](https://github.com/trezor/trezord-go/files/6082204/log.gz)
[trezord.log](https://github.com/trezor/trezord-go/files/6082278/trezord.log)

**Comment by tsusanka** [comment]
I think @bosomt reported something similar? :thinking:

**Comment by prusnak** [comment]
Please test only soon-to-be released 2.0.31. This issue might have been fixed thre.

**Comment by tsusanka** [comment]
I will put 2.0.31 into Suite shortly:tm:.

**Comment by prusnak** [comment]
Btw, this increase is most probably caused by logging. When you go to http://127.0.0.1:21325/status/ there is a log available and you can also download it as a text file. And this log is stored in the memory too.

@slowbackspace can you check how big is the `/Users/maros/Library/Logs/trezord.log` log file?

**Comment by bosomt** [comment]
@prusnak is it possible to start trezord with logging disabled ?

**Comment by prusnak** [comment]
I just noticed the file log rotates after 20 MB and memory log rotates after 90000 lines (where each line can be max 500 characters) ~ 45 MB. 

So logging should not consume that much memory.

**Comment by iMilnb** [comment]
Is this issue even looked at? 1.5G memory usage after 1 week. 2.0.27 is still the official version that's available to download.

**Comment by prusnak** [comment]
> Is this issue even looked at? 1.5G memory usage after 1 week. 2.0.27 is still the official version that's available to download.

We don't provide standalone installers of Bridge anymore. Please uninstall the standalone Bridge and use Trezor Suite which bundles the latest build of Bridge.

**Comment by k3a** [comment]
trezord-go 2.0.31 on Arch Linux:
```
trezord      890  0.0  1.8 2704524 1196060 ?     Ssl  dub12  10:09 /usr/bin/trezord
```
VSZ 2704524
RSS 1196060 that's 1.1 GiB!

Quite a lot for such a tiny Go program.
You should consider adding [pprof](https://jvns.ca/blog/2017/09/24/profiling-go-with-pprof/) to help finding those leaks...
