### ISSUE TITLE
Wallet on own server

### ISSUE THREAD

**Issue by vonProteus** [trezor/trezord-go#228]
hi 
i would like to deploy my own trezor wallet frontend (& backend) but when i try to connect to it its tells me to install bridge which i have installed already
i get 403 from bridge 
i think that is in related with https://github.com/trezor/trezord-go/blob/cde24695535f71de36837d667355855f870ab921/server/api/api.go#L231
i would like to propose flag for trezord which add allowed domain
and maybe don't allow to connect to any other servers 

so person with want to use own backend and frontend would have to add parameter to bridge

**Comment by prusnak** [comment]
We will not be adding this option for security reasons.

Your wallet should use https://github.com/trezor/connect to interact with Trezor devices (so the device requests come from the trezor.io domain)

If you want to use your wallet by yourself you can still use the custom build of Trezor bridge where you add your domain to the list of allowed domains.

**Comment by vonProteus** [comment]
so i cant use 
https://wiki.trezor.io/User_manual:Running_a_local_instance_of_Trezor_Wallet
on my server without recompiling bridge?

**Comment by prusnak** [comment]
You can - just add your server IP to `/etc/hosts` as `YOUR.IP.ADDRESS vonproteus.trezor.io` and use the domain name
