### ISSUE TITLE
Error installing in MacOS high sierra 10.13

### ISSUE THREAD

**Issue by dev-yohan** [trezor/trezord-go#23]
Hi guys I am getting this error trying to install from .pkg file

![screen shot 2018-03-02 at 10 33 41 am](https://user-images.githubusercontent.com/3068138/36901261-4f356b80-1e05-11e8-8531-a3734eb84d6d.png)

any ideas?

regards

**Comment by prusnak** [comment]
Contact our support at https://trezor.io/troubleshooter/
