### ISSUE TITLE
macOS native apple silicon arm packaging and homebrew support

### ISSUE THREAD

**Issue by McCodeman** [trezor/trezord-go#235]
### Feature Request
I would like to run trezord independently as a native apple silicon (arm) process.

### Problem
If I install `trezor-bridge` from the homebrew cask, an Intel compatible (using Rosetta) trezord process is started.
If I run Trezor Suite w/o the `trezor-bridge` installed, a native apple silicon trezord process is started.

### Ask
I'd like to use Trezor with native apple silicon trezord process w/o having to launch Trezor Suite.
Can macOS trezord packaging be updated to include an arm variant and have home brew cask installation select this variant?

### Mitigation
I can use the Intel version until this becomes available or just launch Trezor Suite.
I'm willing to help but very new to this project and may need some pointers on build and packaging process.

Thanks for creating a great product!

**Comment by prusnak** [comment]
> Can macOS trezord packaging be updated to include an arm variant and have home brew cask installation select this variant?

This is becoming more and more problematic with new Apple requirements for notarization. 

I think it makes more sense to rewrite the [Trezor Bridge](https://formulae.brew.sh/cask/trezor-bridge) cask so it builds the bridge from the source. Are you up for this task?

**Comment by McCodeman** [comment]
> I think it makes more sense to rewrite the [Trezor Bridge](https://formulae.brew.sh/cask/trezor-bridge) cask so it builds the bridge from the source. Are you up for this task?

Sure. Let me first attempt to build it locally on macOS.

**Comment by jirkaformanek** [comment]
Nejde to

**Comment by jirkaformanek** [comment]
Hhb

**Comment by igor-hnizdo** [comment]
When removing xgo for mac, I added also ARM support

https://github.com/trezor/trezord-go/pull/258

the notarization thing is not included

**Comment by igor-hnizdo** [comment]
I have included notarization too. I am closing this as it's done in `master` even when it's not yet released, but will be soon-ish.

**Comment by igor-hnizdo** [comment]
Ah, the issue included homebrew too. Reopening.

**Comment by prusnak** [comment]
Homebrew PR in https://github.com/Homebrew/homebrew-core/pull/111672

**Comment by prusnak** [comment]
Homebrew PR has been merged
