### ISSUE TITLE
deb package uses systemd's systemctl

### ISSUE THREAD

**Issue by nagydani** [trezor/trezord-go#24]
The trezord package offered for download for Ubuntu 14.04 LTS relies of systemd's systemctl without explicitly declaring the dependency. This results in an error during installation.  Regular users cannot be expected to work around it. Declaring the dependency would make the installation just fail due to unsatisifed dependency, without messing up the host system. However, it would be even nicer, if you provided a package version for Ubuntu 14.04 LTS, as it is still supported and is quite popular.

**Comment by prusnak** [comment]
Sorry, we don't have enough resources to provide support for 4-year-old system. Anyone can build the bridge from the source.

As for a requirement for systemd, please send a pull request if you know how to add it.

**Comment by faust64** [comment]
Running Devuan, I don't think systemd should be a requirement at all, I'ld rather see the service starting using a traditional initv script when it makes sense.

Besides, the systemd service units shipped implies a trezord user exists, while postinstall didn't create anything like that. I'ld doubt that package even works on a freshly installed system.

**Comment by prusnak** [comment]
@faust64 get to packaging the bridge to your distro then. it's not upstream work to do that for you.

**Comment by prusnak** [comment]
Original issue fixed by 092a8d0a54a5786197edd0588fc22bf64a77da97

Closing

**Comment by faust64** [comment]
I'm a bit busy right now, although I might be able to push something this week ...
