### ISSUE TITLE
Trezor Bridge download link is broken!

### ISSUE THREAD

**Issue by danger89** [trezor/trezord-go#249]
I'm unable to download the Trezor Bridge for AdaLite.

**Steps***

1. When I go to the _official_ download page for the Trezor Bridge: https://suite.trezor.io/web/bridge/
2. I select **Linux 64-bit (deb)**. 
3. Redirect me to the following file: https://data.trezor.iobridge/2.0.27/trezor-bridge_2.0.27_amd64.deb

File/website can **NOT** be found!? What now?

**Comment by aloisklink** [comment]
Try adding a `/` between the `.io` and `bridge`, e.g. https://data.trezor.io/bridge/2.0.27/trezor-bridge_2.0.27_amd64.deb

Btw, you can find a newer version at https://data.trezor.io/bridge/2.0.30/ too.

**Comment by prusnak** [comment]
Right, there is a slash missing between `io` and `bridge`.

Fixed in https://github.com/trezor/trezor-suite/pull/5824 will be deployed soon.

**Comment by danger89** [comment]
Thank you. Follow up item created: #250
