### ISSUE TITLE
Trezor Bridge download not pointing to the latest version 

### ISSUE THREAD

**Issue by danger89** [trezor/trezord-go#250]
The official bridge download page (https://suite.trezor.io/web/bridge/) is not pointing to the latest trezor Bridge version (2.0.30): https://data.trezor.io/bridge/2.0.30/?

It's still pointing to v2.0.27.

**Comment by prusnak** [comment]
This is intended.

**Comment by danger89** [comment]
Owh I see.

**Comment by triceo** [comment]
I'd argue that 2.0.32 is actually a major change: it is the version that makes Trezor Bridge work with Fedora Silverblue. (2.0.27 does not, see https://github.com/trezor/trezord-go/issues/245.) Please publish RPMs for the new version.

**Comment by prusnak** [comment]
> Please publish RPMs for the new version.

We are not going to be publishing new versions as RPM. Please find someone in the Fedora community to maintain the package in the Fedora repository. You are working for Red Hat, there are hundreds of smart people using Fedora there, I think there is a high chance you'll find someone. 🤞 Thanks!
