### ISSUE TITLE
Advertised coins in Features message

### ISSUE THREAD

**Issue by nickoneill** [trezor/trezord-go#27]
Hi there, I'm communicating with the trezor device over usb HID (not technically through trezord, though from a look at trezord-go, it's proxing the same protobuf messages) and successfully getting a Features response back after I send Initialize ('##'). Features lists a bunch of coins that are supported, but Ethereum isn't listed, despite actually being supported.

The list is similar to what is listed here: https://github.com/trezor/trezor-core/blob/master/src/apps/common/coins.py

Is this intentional?

**Comment by prusnak** [comment]
Yes. Coin list only cointains Bitcoin-like coins that use SignTx message and similar.

Ethereum uses EthereumSignTx message. See https://github.com/trezor/trezor-common/blob/master/protob/messages.proto

**Comment by nickoneill** [comment]
Do you have an alternative suggestion for how I detect that a particular device supports ethereum signing in that case? I'm not specifically asking about the `EthereumSignTx` message (I understand I need to use different message types to get different signing behavior), but the one that advertises features supported on the device.

**Comment by prusnak** [comment]
There is no other way than just trying EthereumSignTx and failing with
Unsupported message if it doesn't.
