### ISSUE TITLE
Two directly connected Trezors to macARM M1 are never detected

### ISSUE THREAD

**Issue by bosomt** [trezor/trezord-go#285]
**Describe the bug**
Two directly connected Trezors to mac M1 are never detected.
This behavior is known since 03/2021 when we received our first M1 macbook.
See last screenshot, even suite does not register that i connected T1 and disconnected TT, it still reports TT as connected.
As new macARM architecture is replacing old Intel architecture  maybe we can check and find reason for this behavior.

Problem can be solved by connecting one of devices to hub / usbC to usbMicro adapter does not help/ or by using Chrome and webUSB connection.

**Firmware version and revision**
2.5.2 , 2.5.3, 1.11.x

**Desktop/smartphone setup (please complete the following information):**

 - OS: macOS M1 13.0 and 12.x

**Screenshots**

**2x TT**

<img width="1063" alt="Screenshot 2022-10-27 at 11 44 48" src="https://user-images.githubusercontent.com/31506317/198251865-68087b5b-d889-45f8-9050-e489b61e8f9b.png">

**T1 and TT**
<img width="1073" alt="image" src="https://user-images.githubusercontent.com/31506317/198252004-ab054363-4d9b-42ad-919d-adb697767674.png">

**Only T1 connected**
<img width="1225" alt="image" src="https://user-images.githubusercontent.com/31506317/198252306-e70d4c5e-da1a-472b-9e7f-95f8e7ab07b9.png">

**2x TT - no bridge**
<img width="690" alt="Screenshot 2022-10-27 at 11 53 36" src="https://user-images.githubusercontent.com/31506317/198256726-3b6203f2-8039-4944-b286-64dfde55c2be.png">

**Comment by tsusanka** [comment]
@mroz22 it would be interesting to find out if this happens on your https://github.com/trezor/trezor-suite/pull/6509 branch. As @bosomt writes 

> Problem can be solved ... by using Chrome and webUSB connection.

so my guess is it will not happen there?

**Comment by bosomt** [comment]
tested on https://suite.corp.sldev.cz/suite-web/transport-refactor-2/web/
with standalone bridge 2.0.27
i only see one device connected 
maybe we can retest with app build ? 

<img width="542" alt="image" src="https://user-images.githubusercontent.com/31506317/219312329-91bc1136-3bd9-499f-b002-14465b3d69c1.png">


```
~/Downloads/trezorfwasuite/devkitfw  ioreg -p IOUSB                                                                                                   1 ✘  took 56s
+-o Root  <class IORegistryEntry, id 0x100000100, retain 29>
  +-o AppleT8103USBXHCI@00000000  <class AppleT8103USBXHCI, id 0x1000002c8, registered, matched, active, busy 0 (67248 ms), retain 84>
  | +-o TREZOR@00100000  <class IOUSBHostDevice, id 0x10003ac7c, registered, matched, active, busy 0 (19 ms), retain 23>
  +-o AppleT8103USBXHCI@01000000  <class AppleT8103USBXHCI, id 0x10000029b, registered, matched, active, busy 0 (50055 ms), retain 92>
    +-o TREZOR@01100000  <class IOUSBHostDevice, id 0x10003ac38, registered, matched, active, busy 0 (43 ms), retain 31>
```

**Comment by tsusanka** [comment]
Yes please try with desktop and Bridge turned off.

**Comment by bosomt** [comment]
same result with 2.0.32 + this branch binary :(

**Info:**
 - Suite version: desktop 23.3.0 (8219f5c62d380a3be25dc8cfc51dad10a427b51e)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.3.0 Chrome/104.0.5112.124 Electron/20.3.12 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.3 Bitcoin-only (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: BridgeTransport 2.0.32

**Comment by tsusanka** [comment]
But that seems you are still using Bridge. And this branch it should not be needed. Maybe you have to set "nodeUSB" in debug settings?

**Comment by bosomt** [comment]
Disabled bridge in debug but Trezor is not detected in Suite /even after restart / and of course Suite reports that Bridge is not running.
Maybe we have to change Bridge detection behavior too ?

<img width="601" alt="image" src="https://user-images.githubusercontent.com/31506317/219902573-8510aacb-bcc9-4feb-9428-b0bebde88444.png">

<img width="304" alt="image" src="https://user-images.githubusercontent.com/31506317/219902577-baff7d14-8d6d-41f2-9bdc-42fefe83e07f.png">

```
  +-o AppleT8103USBXHCI@01000000  <class AppleT8103USBXHCI, id 0x10000029b, reg$
    +-o TREZOR@01100000  <class IOUSBHostDevice, id 0x100043bed, registered, ma$
 ```

**Comment by bosomt** [comment]
**QA OK**

NICE!

**Info:**
 - Suite version: desktop 23.3.0 (8219f5c62d380a3be25dc8cfc51dad10a427b51e)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.3.0 Chrome/104.0.5112.124 Electron/20.3.12 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.3 Universal (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: NodeUsbTransport

<img width="504" alt="image" src="https://user-images.githubusercontent.com/31506317/219909447-150e5c05-3506-4004-b70b-ed51ee018bcf.png">

```
 ~  ioreg -p IOUSB                                                         ✔
+-o Root  <class IORegistryEntry, id 0x100000100, retain 29>
  +-o AppleT8103USBXHCI@00000000  <class AppleT8103USBXHCI, id 0x1000002c8, reg$
  | +-o TREZOR@00100000  <class IOUSBHostDevice, id 0x1000450da, registered, ma$
  +-o AppleT8103USBXHCI@01000000  <class AppleT8103USBXHCI, id 0x10000029b, reg$
    +-o TREZOR@01100000  <class IOUSBHostDevice, id 0x1000450c1, registered, ma$
 ```

**Comment by tsusanka** [comment]
Mega cool! cc @mroz22 

@sime another reason to kill Bridge 😛.

**Comment by matejkriz** [comment]
I'm reopening because the bridge issue is not resolved. It works fine with NodeUSB and that just proves that it's a bridge bug and not macos.

**Comment by MiroslavProchazka** [comment]
Will be solved by introducing node usb transport as primary. @mroz22
