### ISSUE TITLE
On macOS 13.3 bridge shows 1 device as 2 devices

### ISSUE THREAD

**Issue by matejkriz** [trezor/trezord-go#288]
Bridge 2.0.32
macOS 13.3.0/13.3.1

- connect just one device (no matter if model T or model One)

- check status page http://127.0.0.1:21325/status/

![image (5)](https://user-images.githubusercontent.com/3729633/231469155-ea6bb9c7-eea2-49d7-b15f-f9d649f5faff.png)

Expected:
- see just the 1 device connected

Actual:
- there is one more weird device shown

detailed logs:
[log (1).gz](https://github.com/trezor/trezor-suite/files/11211989/log.1.gz)

**Comment by karelbilek** [comment]
Based on the logs and the picture, the hidapi layer (that is there "just" for old devices) is somehow catching the new device

Can you try to merge this and send the log again? It seems there is no detailed logging for hidapi layer

#289

**Comment by karelbilek** [comment]
the PR log might actually be leaking some private info so better not to actually merge it...

**Comment by karelbilek** [comment]
The bug will be somewhere there with the HID matching logic. But any fix would need to be re-tested with old HID devices on Mac and Windows to make sure it doesn't break something (not Linux, that is not using HIDAPI)

**Comment by karelbilek** [comment]
I _think_ the easy fix would be to just remove the `trezor2:=...`; it doesn't use HID anyway. No idea why the new macos started showing it in the list _now_; maybe some combination of macos behaviour and hidapi code behaviour

**Comment by matejkriz** [comment]
new logs from https://github.com/trezor/trezord-go/pull/289/commits/73f1140b80e55696bbd4d23ea282598fd9f310ac 
[log (2).gz](https://github.com/trezor/trezord-go/files/11213456/log.2.gz)

![image](https://user-images.githubusercontent.com/3729633/231513979-ba3b757d-cacb-4be7-ad41-4e307880aa61.png)

**Comment by matejkriz** [comment]
@trezor/qa please check PR description for notes for testing https://github.com/trezor/trezor-suite/pull/8100

**Comment by bosomt** [comment]
**QA OK**

tested and released to 23.4.2



**Info:**
 - Suite version: desktop 23.4.2 (5c5b3c885c52c38f3c8115fed07c2faf6a77fc7a)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.4.2 Chrome/110.0.5481.208 Electron/23.2.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.6.0 Universal (revision 88e1f8c7a5c7615723664c64b0a25adc0c409dee)
 - Transport: BridgeTransport 2.0.33
