### ISSUE TITLE
Initialize didn't respond

### ISSUE THREAD

**Issue by szymonlesisz** [trezor/trezord-go#29]
Steps to reproduce (chrome + macos):

1. Connect T2 (unlock pin)
2. Go to wallet (let the wallet read accounts)
3. Refresh wallet with console opened
4. When device is in initialize process refresh again (you need to be quick enough and do it before Initialize response from bridge)
5. After wallet reloads device will be in unacquired state, and [trezor.js] [call] Sending Initialize {} will never be resolved.

I'm putting this issue here, but i'm not sure which layer is responsible for that (bridge or trezor-link)

**Comment by chren-de-large** [comment]
Happens similar to me (macOS 10.13.3), most probably TREZOR Link does not propagate release/disconnect and get stucked on ghost device.

Trezor Connect: 5.0.6 uses Link v. 1.3.8 and TREZOR Bridge v 2.0.9

[trezord.log](https://github.com/trezor/trezord-go/files/1802749/trezord.log)


![screen shot 2018-03-12 at 1 37 59 pm](https://user-images.githubusercontent.com/1671375/37284291-47487b62-25fb-11e8-8dd8-a98700892746.png)

**Comment by szymonlesisz** [comment]
I'm pretty sure it's not caused by bridge. I have same issues with WebUSB transport:

[trezor.js] [device list] Configuring transports
app.28e7f6c4b6fd61b24b6f.js:1 [trezor.js] [device list] Configuring transports done
app.28e7f6c4b6fd61b24b6f.js:1 [trezor.js] [device list] Creating Device Object undefined
app.28e7f6c4b6fd61b24b6f.js:1 [trezor.js] [call] Sending Initialize Object
app.28e7f6c4b6fd61b24b6f.js:1 [trezor.js] [call] Received Features Object
app.28e7f6c4b6fd61b24b6f.js:1 [trezor.js] [session] releasing
app.28e7f6c4b6fd61b24b6f.js:1 [DeviceUpdate] action: 
app.28e7f6c4b6fd61b24b6f.js:1 [DeviceUpdate] progress: initial
app.28e7f6c4b6fd61b24b6f.js:1 [trezor.js] [call] Sending Initialize Object
app.28e7f6c4b6fd61b24b6f.js:1 [trezor.js] [call] Received Features Object
**app.28e7f6c4b6fd61b24b6f.js:1 [trezor.js] [call] Sending GetPublicKey Object
app.28e7f6c4b6fd61b24b6f.js:1 [trezor.js] [call] Received Features Object**
app.28e7f6c4b6fd61b24b6f.js:1 [trezor.js] [session] releasing

**Comment by szymonlesisz** [comment]
moving here:
https://github.com/trezor/trezor-core/issues/175
