### ISSUE TITLE
v2.0.33 reports its version as v2.0.34

### ISSUE THREAD

**Issue by p-linnane** [trezor/trezord-go#292]
Hello 👋 . I'm a maintainer for the [Homebrew](https://brew.sh) project. While packaging v2.0.33 of Trezor Bridge, we ran into a failure when performing our testing. The release was tagged with a [commit](https://github.com/trezor/trezord-go/commit/33e9b0973b696cfa2f0376ce80fdee79a3a0646c) which marks the current version as v2.0.34. This prevents us from verifying that it built correctly.

Relates to https://github.com/Homebrew/homebrew-core/pull/128594

**Comment by tsusanka** [comment]
My bad 🤦. Will force-push the git tag.

**Comment by tsusanka** [comment]
Fixed! Apologies and thank you for taking care of homebrew!

**Comment by p-linnane** [comment]
Latest build succeeded. Thanks again!
