### ISSUE TITLE
Unstable connection in Windows 10

### ISSUE THREAD

**Issue by slush0** [trezor/trezord-go#31]
Multiple users reported weird behavior of Trezor (both One and Model T) in Windows 10:

a) Takes many minutes to appear in wallet.
b) Disconnects after some time of usage.

https://www.reddit.com/r/TREZOR/comments/818q1d/trezor_wont_connect_to_mew/dvasijw/

Another guy reported over Telegram.

**Comment by slush0** [comment]
/u/interslicer reported both T1 and TT have issues in Bridge (even if Extension is disabled), but T1 works nicely in Extension. So it doesn't look like anything driver- or OS-related.

**Comment by karel-3d** [comment]
I cannot replicate, so not sure what to do here

**Comment by karel-3d** [comment]
2.0.11 will have more explicit error logging, that might help.

**Comment by karel-3d** [comment]
I would wait for 2.0.11, which adds the win10 fixes and more error logging, and test it again

**Comment by prusnak** [comment]
Binaries from https://github.com/trezor/webwallet-data/tree/master/bridge/2.0.11 should fix the issue, please reopen if they don't.
