### ISSUE TITLE
Add status page

### ISSUE THREAD

**Issue by slush0** [trezor/trezord-go#32]
Currently, people have no user feedback that the Bridge is running and operational, which makes our customer support blind while debugging connection issues. I propose to implement page on http://localhost:21325/, which will inform user that:

a) Bridge is installed and running
b) Bridge version
c) What devices it see

Security consideration: who can display this page? Only origin: null? Is that safe enough and/or are information displayed on the page sensitive enough to protect them in any other way?

**Comment by prusnak** [comment]
Implemented in 2.0.11
