### ISSUE TITLE
Malformed wire format

### ISSUE THREAD

**Issue by slush0** [trezor/trezord-go#34]
Some users reported "Malformed wire format", which is an error message from Bridge.

https://www.reddit.com/r/TREZOR/comments/84k7u9/action_was_interrupted_error_details_malformed/

https://www.reddit.com/r/TREZOR/comments/82ryyo/connect_trezor_to_continue_error_model_t/

What may be the cause for such message? Two clients/tabs talking to the device? How can we prevent it or recover from such state?

**Comment by marekbatelka** [comment]
@slush0, I have this issue on my device if you need more info or test.
my batch 300-7046 09/2018, boot loader 2.0.1 firmware 2.0.5.
window 10 64b

I observe on https://beta-wallet.trezor.io it connects fine.

If I open new tab with https://wallet.trezor.io (nobeta), 

while still connected on first tab (beta) I try to connect on non beta tab.
I get in beta-wallet tab this message:.
> Failed to renew session.
> Error details: malformed wire format

and in NonBeta window:
> Reading of accounts failed.
> Error details: Error: The action was interrupted by another application.

I am not able to connect to https://wallet.trezor.io, trezor T works only on https://beta-wallet.trezor.io

Also I am not able to connect to Password manager. Probably password manager not supported with trezor T?

**Comment by marekbatelka** [comment]
Another occurence is reproducible with beta-wallet, when multiple switches between different currencies

Steps to reproduce:
Using Trezor T, batch 300-7046 09/2018, boot loader 2.0.1 firmware 2.0.5., windows 10 64b

- Login to beta-wallet.trezor.io
- starting at bitcoin
- switch to litecoin 
- click bitcoin quickly before page finishes loading.

Observed error:
```
Action was interrupted
Error details: malformed wire format
```

`Logs: ["log","Thu, 15 Mar 2018 19:27:26 GMT","[app] User agent : ","Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36"]
["log","Thu, 15 Mar 2018 19:27:26 GMT","[CoinInfo] Done reading coin; BTC"]
["log","Thu, 15 Mar 2018 19:27:26 GMT","[CoinInfo] Current backend URL : https://btc-bitcore3.trezor.io"]
["log","Thu, 15 Mar 2018 19:27:26 GMT","[trezor.js] [device list] Initializing transports"]
["log","Thu, 15 Mar 2018 19:27:26 GMT","[trezor.js] [device list] Configuring transports"]
["log","Thu, 15 Mar 2018 19:27:26 GMT","[trezor.js] [device list] Configuring transports done"]
["log","Thu, 15 Mar 2018 19:27:26 GMT","[trezor.js] [device list] Creating Device",{"path":"web03","session":null,"product":21441,"vendor":4617},null]
["log","Thu, 15 Mar 2018 19:27:27 GMT","[trezor.js] [call] Sending","Initialize",{}]
["log","Thu, 15 Mar 2018 19:27:27 GMT","[trezor.js] [call] Received error","Error: malformed wire format"]
["log","Thu, 15 Mar 2018 19:27:27 GMT","[trezor.js] [session] releasing"]
["log","Thu, 15 Mar 2018 19:27:27 GMT","[deviceList] Catched error, printing stack"]
["log","Thu, 15 Mar 2018 19:27:27 GMT","Error: malformed wire format"]
["log","Thu, 15 Mar 2018 19:27:27 GMT","Error: malformed wire format\n    at https://beta-wallet.trezor.io/app.28e7f6c4b6fd61b24b6f.js:1:778893\n    at w (https://beta-wallet.trezor.io/app.28e7f6c4b6fd61b24b6f.js:1:2629111)\n    at Generator._invoke (https://beta-wallet.trezor.io/app.28e7f6c4b6fd61b24b6f.js:1:2628899)\n    at Generator.e.(anonymous function) [as next] (https://beta-wallet.trezor.io/app.28e7f6c4b6fd61b24b6f.js:1:2629290)\n    at r (https://beta-wallet.trezor.io/app.28e7f6c4b6fd61b24b6f.js:1:779098)\n    at https://beta-wallet.trezor.io/app.28e7f6c4b6fd61b24b6f.js:1:779192\n    at <anonymous>"]
["debug","Thu, 15 Mar 2018 19:27:27 GMT","[trezor.js] [device list] Cannot create device","Error: malformed wire format"]`

**Comment by slush0** [comment]
Thank you @marekbatelka. One question - do you have installed Trezor Chrome extension? If you do, can you please disable it and try again?

**Comment by marekbatelka** [comment]
TCE and TPM extensions removed

wallet.trezor.io started to work and now I can be even connected in multiple tabs with beta and non beta (it was not case before).
![image](https://user-images.githubusercontent.com/2838809/37490584-4f750d26-289b-11e8-93b1-516cc84fe42a.png)

I reinstalled TCE in order to reproduce issue, but not able to reproduce. Now it works with TCE active in both... strange...

Anyway,
I am still able to reproduce "malformed wire format" with fast switching currencies. TCE disable or enabled doesn´t seem to be a difference. This will disconnect device and I have to reconnect USB again.

btw, I got confirmation from support team (Leo), that TPM is not compatible with Trezor T. will wait for new interface.

**Comment by slush0** [comment]
Password manager is not compatible, because it works only with Extension, which is not implementing Model T protocol. We're working on Bridge support for Password manager, then it will work for Model T, too.

Back to the topic: Okay, we had suspicion that it may be an Extension conflicting to Bridge, which seems to be (at least part of) the issue. Please keep Extension disabled (if possible) and report later, if it really fixed the most common problems.

That reloading of coins may be similar problem, we'll investigate more in depth tomorrow.

**Comment by marekbatelka** [comment]
Understood for PM. sorry for offtopic, I thought it might be connected.
Didn´t know about incompatibility before.

Extension is disabled for now, but I cannot say for sure if it fixed the
issue, because it started to work with extension enabled or disabled. (In
both cases it works now.)

Looking forward reloading of coins issue (this is only remaining which can
be still reproduced.)

Thank you

2018-03-15 22:27 GMT+01:00 slush0 <notifications@github.com>:

**Comment by marekbatelka** [comment]
One more way how to brake the connection and get 
> Action was interrupted
> Error details: malformed wire format


- Go to beta-wallet.trezor.io
- enter pin on Trezor
- while Trezor shows Loading
- click on wallet in menu (this will bring you to wallet.trezor.io)

Actual behavior:
Error appears and Trezor is disconnected.
![image](https://user-images.githubusercontent.com/2838809/37492913-6711091e-28a3-11e8-8053-cef9e707538e.png)

Expected: Connection shall be re-established (recovered) without need to reconnect Trezor physically to USB.

This is same issue as with Coins switching. 
Looks like connection is interrupted if session is not finished completely.

**Comment by georgeapostolov** [comment]
I have the same problem when trying to connect to NanoWallet with Trezor.

After installing trezor-bridge-2.0.9-win32-install.exe I was getting the same "malformated wire format" error.

Now with trezor-bridge-2.0.10-win32-install I am getting "Failed to create wallet, reason: Unexpected message"

It's not working on my Trezor T. I have no problems with the old Trezor. There its working just fine.

**Comment by prusnak** [comment]
NEM is not supported on Model T yet, so the problem you see is unrelated
to communication problems and I would say that your communication
problem is solved even.

**Comment by karel-3d** [comment]
@marekbatelka can you click on "show log" (not console, but "show log" on the bottom of the webpage) on both beta wallet and non-beta wallet and tell me the first line of the two logs? They show which transport is loaded

**Comment by marekbatelka** [comment]
Transport: bridge 2.0.10 on both.
I have Chrome Plugin removed.

If this is not what you are looking for, could you clarify which scenario
you want to test? Switch of currencies or wire malfunction on connect?

Thanks!

2018-03-20 12:39 GMT+01:00 Karel Bílek <notifications@github.com>:

**Comment by karel-3d** [comment]
Thanks, I probably fixed it here, thanks for the report.

https://github.com/trezor/trezord-go/pull/39

**Comment by marekbatelka** [comment]
Issue with connection is fixed no longer problem, but still switching between currencies raises this error.

**Comment by karel-3d** [comment]
Have you tested latest 2.0.11 bridge from master? We did not release the binaries yet publicly, you can probably build it yourself

**Comment by marekbatelka** [comment]
I don´t have knowledge to build bridge myself. Will wait. This was with
2.0.10.


2018-03-26 13:46 GMT+02:00 Karel Bílek <notifications@github.com>:

**Comment by prusnak** [comment]
@marekbatelka Try the new 2.0.11 bridge from here: https://github.com/trezor/webwallet-data/tree/master/bridge/2.0.11 and please report back if that fixed the issue. If not, please reopen.

**Comment by marekbatelka** [comment]
@prusnak @karel-3d @slush0 @georgeapostolov tested and switching of currencies works with Bridge 2.0.11.
 **Issue fixed.**
Thank you, guys!
