### ISSUE TITLE
Add init.d scripts for non-systemd linuxes

### ISSUE THREAD

**Issue by slush0** [trezor/trezord-go#35]
Although systemd is more or less a standard in linux world, some users are reporting "bridge doesn't start" due to missing init.d script. Although it is for backward compatibility only, I think it is reasonable to include init.d script.

**Comment by Mustard5** [comment]
Tried installing the bridge today on Linux Mint 17.3 LTS release and encountered errors related to not finding 'systemctl'.  I'm fairly certain this relates to the bug reported by user slush0 above.  This Long Term Service release is being supported until 2019, so I don't expect to update until after that date.

It would be appreciated if I could retain functionality of my Trezor device until this release of Linux Mint has run its course.

Could you please include support for init.d?

**Comment by karel-3d** [comment]
If we add an init.d script, we will have to keep maintaining an init.d script.

**Comment by prusnak** [comment]
It's the job of these distributions and their maintainers to provide a package (most of them already do) if they decide not to ship with systemd.
