### ISSUE TITLE
Action was interrupted error on Windows Server 2008 / Windows 7

### ISSUE THREAD

**Issue by pankrats** [trezor/trezord-go#38]
User gets "Action was interrupted Error details: device not found" error when opens beta-wallet.trezor.io with TREZOR T. 

Operating system:  Windows Server 2008 / Windows 7

_Bootloader mode, Wipe out and install firmware is working. 
The windows drivers are up to date.
The trezor reboots but the web page is still showing "Waiting for TREZOR to reboot"_ 

[Action interrupted_Log.txt](https://github.com/trezor/trezord-go/files/1828704/Action.interrupted_Log.txt)

![trezor-chrome](https://user-images.githubusercontent.com/31442634/37647176-e986524c-2c2b-11e8-8a31-5cfd784e3910.png)

**Comment by karel-3d** [comment]
Can you try it again with 2.0.11 ?

 https://github.com/trezor/webwallet-data/tree/master/bridge/2.0.11 

If it still happens, can you please post log from the new bridge status page - that is, from http://127.0.0.1:21325/

**Comment by tolotos-rgu** [comment]
I found the error:
Zadig has a option show all devices. It shows two Trezor devices one had a wrong driver. I reinstalled WinUSB driver for this device and not the trezor is working.

Thanks! You can close this issue from my side.
