### ISSUE TITLE
Possibility to run on windows without admin?

### ISSUE THREAD

**Issue by karel-3d** [trezor/trezord-go#40]
Research if it is possible to run on windows without admin rights, and why not if not.

note: it is possible to run as user on macOS and linux, but not install.

**Comment by AreDubya** [comment]
If any testing on a Windows 10 system would be helpful I would be happy to help.

**Comment by karel-3d** [comment]
I am closing this.

Yes, it is apparently possible to run on Win8+ without admin rights, if you remove the UAC escalation from NSIS config.

However. We need UAC escalation because of Windows 7 driver issues, and you cannot set "conditional" UAC escalation based on Windows version in NSIS (the requested execution level is in the EXE itself).

It could maybe be done by some shell script/power shell hacks, but that would further complicate the already quite crazy installation.
