### ISSUE TITLE
not emitting disconnect msg / ghost device?

### ISSUE THREAD

**Issue by chren-de-large** [trezor/trezord-go#44]
I have experienced familiar buggy behavior of Bridge Version: 2.0.11 on MacOS 10.13.3.

Very rarely the device is not emitting disconnect message via latest Connect and is acting like stilll connected device until next action (after hitting cipherKeyValue) bridge send disconnect message and everything seems fine.

log attached
[log.txt](https://github.com/trezor/trezord-go/files/1848287/log.txt)

**Comment by karel-3d** [comment]
How to best replicate this? It does not seem to happen to me

**Comment by karel-3d** [comment]
Is this still happening, with the latest bridge?

If so, can you post the long log from the status page?

**Comment by chren-de-large** [comment]
not anymore, close please
