### ISSUE TITLE
Publish the keyId used to sign the Windows installer

### ISSUE THREAD

**Issue by bigcoinme** [trezor/trezord-go#49]
Hello,
I'd like to verify the integrity of the Trezor Bridge Installer for Windows using GPG4Win but, for doing that, I need the keyId that Trezor used to sign the Windows installer.
Could you publish it so that we can verifiy the integrity of the Trezor Bridge Windows installer, please?
Thanks in advance.
Kind regards,

Rodrigo

**Comment by prusnak** [comment]
86E6 792F C27B FD47 8860  C110 91F3 B339 B9A0 2A3D

**Comment by bigcoinme** [comment]
Thanks 0x91f3b339b9a02a3d
