### ISSUE TITLE
Provide 64-bit binary for Windows

### ISSUE THREAD

**Issue by prusnak** [trezor/trezord-go#50]
Now that https://github.com/trezor/trezord-go/commit/85130c87d49dd9552333ea46f3872a25fd162a37#diff-1d20e50206f89bd7dbcde546607a187aR43 introduced x32/x64 condition we can as well provide 64-bit bridge binary in the same installer.

**Comment by karel-3d** [comment]
I thought we already do?

**Comment by karel-3d** [comment]
Yep here it shows that trezord is already 64b

https://github.com/trezor/trezord-go/blob/master/release/windows/trezord.nsis#L87
