### ISSUE TITLE
Can this project be run on travis?

### ISSUE THREAD

**Issue by afk11** [trezor/trezord-go#53]
I'm writing a bridge to this API, and am working on integration testing the library: https://github.com/Bit-Wasp/trezor-bridge-client I figure that the trezor emulator and the trezord-go binary should be enough for this, but I seem to get an error with starting the USB layer on travis. 

Considering just patching those lines out for my test, but I'm curious if you've run into this before or what your solution was!

https://travis-ci.org/Bit-Wasp/trezor-bridge-client/jobs/363476849#L3117

**Comment by karel-3d** [comment]
Interesting, a good point. I haven't tried it, it's possible that the
libusb throws some random error on initialization.

I suppose you want to run it with UDP t1/t2 emulator, right?

I will add add an option to not have the USB transports available and only
use udp, similar to the current -e option.

**Comment by afk11** [comment]
I wrote up this branch if it's acceptable? It does work for me and it'd be nice to have it upstream :) https://github.com/trezor/trezord-go/compare/master...Bit-Wasp:nousb

**Comment by karel-3d** [comment]
I don't have an experience with debug link :(, but it should work

**Comment by afk11** [comment]
Yea it does work mostly, it causes some weird problems when you use DebugLinkDecision though because the device doesn't return a response. I would be tempted to add a header that causes the `devReadWrite` not to try to read a response, otherwise that request never completes which causes hassle of HTTP libs.

**Comment by karel-3d** [comment]
Nice ideas

Please check this branch if it's good. If it works for you, I will merge

https://github.com/trezor/trezord-go/pull/56

**Comment by afk11** [comment]
Fantastic, yes this does the trick! Thanks for your help, I think this covers everything. I'll see how for I can get with the integration tests now :+1:

**Comment by karel-3d** [comment]
Cool, merging.

**Comment by karel-3d** [comment]
Master now. If there any more problems, please write. (And post here where you actually use it, I am interested :D )

**Comment by afk11** [comment]
Awesome, thanks a lot! 
Project (in PHP): https://github.com/bit-wasp/trezor-bridge-client
Helper scripts for testing: https://github.com/Bit-Wasp/trezor-bridge-client/tree/master/tool 
 * build_bridge.sh builds the trezord-go, but you gotta set BRIDGE_PATH manually (whatever suits your go env)
 * build_emulator.sh clones trezor-mcu and runs the ./build-emulator.sh from that project
 * run_integration_tests wraps these, and starts test cases

Then there's a test case class which boots/kills the bridge & emulator, giving me a clean environment each time https://github.com/Bit-Wasp/trezor-bridge-client/blob/master/test/device/TestCase.php 

Have one or two tested in the repo already, have yet to get to it again since checking the your patch yesterday: https://github.com/Bit-Wasp/trezor-bridge-client/blob/master/test/device/AcquireDeviceTest.php#L17 not much free time for the next few days, but will be adding more integration tests soon not that I can interact with buttons, etc!

**Comment by karel-3d** [comment]
I might be dense, what is that PHP project for?

Is that for communication with device which is on the server? What is the usecase?

**Comment by afk11** [comment]
No definite usecase, just starting with the wrapper for now! There are bitcoin libraries in PHP, so would be interested in how hard it is to make use of the trezor under the hood, especially for signing. You can bet if no ones even asked yet, they'll be handling private keys directly..
