### ISSUE TITLE
Qubes 4.0 (Fedora 26 template) - Model T connection problems

### ISSUE THREAD

**Issue by pruflyos** [trezor/trezord-go#59]
I'm running Qubes OS 4.0 (Fedora 26 template) and experience connection problems only with the `Model T` while `Trezor One` works fine.

I'm using `trezor-bridge-2.0.12-1.x86_64.rpm`.
Model T firmware: `2.0.6`

**What's the exact problem?**
It seems like the `Model T` is connected for a second in the `beta-wallet` (Chromium) via trezord, but then the following error is shown:
```
Action was interrupted
Error details: The device was disconnected.
```
`Trezor One` works fine on that system.

I also tried the `Model T` with different cables and on different USB ports, always the same issue. And I checked the `Model T` on another  Ubuntu 16.04, where  it works fine. So it's either the `trezord` on Fedora 26 which is causing this, or a rare firmware issue with the `Model T` which is only present on Fedora 26 (Qubes 4.0)?

trezord output:
```
$ trezord
2018/04/21 16:51:44 trezord is starting.
2018/04/21 16:51:50 POST /
127.0.0.1 - - [21/Apr/2018:16:51:50 -0400] "POST / HTTP/1.1" 200 21
2018/04/21 16:51:50 POST /enumerate
127.0.0.1 - - [21/Apr/2018:16:51:50 -0400] "POST /enumerate HTTP/1.1" 200 3
2018/04/21 16:51:51 POST /listen
127.0.0.1 - - [21/Apr/2018:16:51:51 -0400] "POST /listen HTTP/1.1" 200 64
2018/04/21 16:52:08 POST /listen
2018/04/21 16:52:08 POST /acquire/web01/null
2018/04/21 16:52:12 Warning: error at device reset: LIBUSB_ERROR_NOT_FOUND
2018/04/21 16:52:12 Warning: error at configuration set: LIBUSB_ERROR_NO_DEVICE
2018/04/21 16:52:12 Returning error: device not found
127.0.0.1 - - [21/Apr/2018:16:52:08 -0400] "POST /acquire/web01/null HTTP/1.1" 400 29
127.0.0.1 - - [21/Apr/2018:16:52:08 -0400] "POST /listen HTTP/1.1" 200 3
2018/04/21 16:52:16 POST /listen
```

dmesg output:
```
[ 2517.644162] usb 1-1: SetAddress Request (34) to port 0
[ 2517.667220] usb 1-1: New USB device found, idVendor=1209, idProduct=53c1
[ 2517.667287] usb 1-1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[ 2517.667329] usb 1-1: Product: TREZOR
[ 2517.667353] usb 1-1: Manufacturer: SatoshiLabs
[ 2517.667395] usb 1-1: SerialNumber: XXXXXXXXXXXXXXXXXXXXXXXX
[ 2517.682497] hid-generic 0003:1209:53C1.000C: hiddev96,hidraw0: USB HID v1.11 Device [SatoshiLabs TREZOR] on usb-vhci_hcd.0-1/input1
[ 2525.985061] vhci_hcd: vhci_device speed not set
[ 2526.191132] vhci_hcd: vhci_device speed not set
[ 2526.399124] vhci_hcd: vhci_device speed not set
[ 2526.607101] vhci_hcd: vhci_device speed not set
[ 2526.815132] vhci_hcd: vhci_device speed not set
[ 2526.815208] usb usb1-port1: Cannot enable. Maybe the USB cable is bad?
...
[ 2533.351197] usb usb1-port1: Cannot enable. Maybe the USB cable is bad?
[ 2533.351274] usb usb1-port1: unable to enumerate USB device
```

**Comment by prusnak** [comment]
Can you try regular Fedora 26 (no Qubes) so we can narrow down
the issue?

**Comment by pruflyos** [comment]
Unfortunately not. But I tried with the `Debian 9` template and get exactly the same error and symptoms.

What's strange is, that `python-trezor` alias `trezorctl` works fine with the `Model T`. Same with `trezor-agent`, I can use gnupg with the `Model T` without problems... so it's only the `trezor-bridge` which is having  these problems with the `Model T` and Qubes (Xen).

**Comment by ddeath** [comment]
@pruflyos this is probably problem with Fedora. My colleague has similar problem yesterday when the trezor returns: `"POST /acquire/web01/null HTTP/1.1" 400 29`

Also with message: `LIBUSB_ERROR_NOT_FOUND`
It can be related to shell which you are using, for example: https://github.com/mitshell/CC2531/issues/5

The dirty hack which worked in our case (may be not safe to use) was running `trezord-go` as root:
`sudo ./trezord-go`

In our case the `LIBUSB_ERROR_NOT_FOUND` was referencing to some read permission error...

**Comment by prusnak** [comment]
Seems like you need to configure SELinux properly on Fedora. Not sure
that is causing the issue on Qubes.

**Comment by pruflyos** [comment]
Since everything works fine in Qubes with a `Trezor One` and the `Model T` on the other hand works fine on other operating systems, my current quess is it's an USB 3.0 issue with Qubes. While the `Trezor One` is a USB 2.0 device, the `Model T` is USB 3.0, right?

Qubes uses a component called `qubes-usb-proxy` (https://github.com/QubesOS/qubes-app-linux-usb-proxy) for passthrough of USB devices to other VMs. Maybe there's either a generic problem with USB 3.0 devices or with the `Model T` specifically.

I guess I should open an issue in the Qubes project...

**Comment by prusnak** [comment]
> the Model T is USB 3.0, right?

No, Model T is USB 1.1 device just like Trezor One.

**Comment by ljarasius** [comment]
Bumped into this one myself with my Model T on Arch, make sure udev was installed also, as it did not prompt me, then make sure these rules are added: https://doc.satoshilabs.com/trezor-user/settingupchromeonlinux.html
Hope that helps solve this problem :)

**Comment by prusnak** [comment]
Not sure what else we can do here.
