### ISSUE TITLE
Include whitelist from bridgeV1/chrome app.

### ISSUE THREAD

**Issue by destrys** [trezor/trezord-go#64]
I think the url whitelist from the old bridge and chrome app isn't included in this new bridge.
I see here the restriction to trezor.io and localhost: 
https://github.com/trezor/trezord-go/blob/master/server/http.go#L112

We were on the old whitelist and I'm seeing a 403 from the bridge after upgrading to V2.

Here is our PR for joining the whitelist originally: 
https://github.com/trezor/trezor-common/pull/49

**Comment by prusnak** [comment]
Whitelist is not coming to V2 as the old method will be deprecated. If you want to continue using TREZOR, use https://github.com/trezor/connect for integration.
