### ISSUE TITLE
Stuck on version 2.0.12

### ISSUE THREAD

**Issue by rgruesbeck** [trezor/trezord-go#65]
Following the build instructions gives me version 2.1.12.
I'm getting the version by running trezord-go and visiting http://localhost:21325/ in the browser.
(would be great to have a -version flag)

- go1.10.2 linux/amd64

I was able to build version 2.1.13 with the golang docker image but the wallet was not able to detect that trezord was running displayed the "not installed" message.

**Comment by prusnak** [comment]
Please reopen if you still have the same problem
