### ISSUE TITLE
Bridge not found in KDE Neon

### ISSUE THREAD

**Issue by kenj70** [trezor/trezord-go#66]
Up-to-date KDE Neon 5.12.5 based on ubuntu 16.04 LTS

I have been successfully using the Trezor extension in Chromium for eight months. Heeding the warning to begin using Trezor Bridge I installed 2.0.13 but can't connect with Chromium 66. Tried Firefox 60.0.1 and still not recognized. The trezord is running. Finally, I tried Brave 0.22.714 and it works!

I haven't started using Brave yet and would prefer to use Chromium. Why would a browser based on the Chromium code base work but not Chromium? Naturally I am a little nervous about removing my Trezor extension just yet.

**Comment by prusnak** [comment]
My guess is that you use some extension that block communication with
the bridge, such as AdBlock or PrivacyBadger.

**Comment by kenj70** [comment]
OMG! I never thought that could be an issue. Brave has no add blocker installed yet. Chromium and Firefox have Ghostery. Trusting the mytrezor page enables full operation. Thank you!

-=Ken=-
