### ISSUE TITLE
Allow requests from node (No origin)

### ISSUE THREAD

**Issue by wbobeirne** [trezor/trezord-go#68]
I was trying to use `trezor.ts` in my node application, but Bridge v2 was rejecting requests to it with 403. After some digging, I found that the CORS validator was supposed to allow this, but had it commented out: https://github.com/trezor/trezord-go/blob/2b2bcd295d93f4c130c16e7ce3d173bceb5fe1e5/server/api/api.go#L219 Is there any reason this was removed? Can it be added back in?

Initial issue was over at https://github.com/trezor/trezor-link/issues/7

**Comment by wbobeirne** [comment]
Just an additional note of context, this comment: https://github.com/trezor/trezor.js/issues/37#issuecomment-360850540 said that bridge would continue to support requests from node, so ideally this should make its way back in.

**Comment by prusnak** [comment]
Will be closed via #68
