### ISSUE TITLE
Where are the tests?

### ISSUE THREAD

**Issue by rfjakob** [trezor/trezord-go#71]
I'm looking at integrating Trezor support into [gocryptfs](https://github.com/rfjakob/gocryptfs). And I'm thinking about using trezord-go to handle the USB side of things to keep the code in gocryptfs simple.

Now, maybe I'm missing something, but does this project really have zero tests?

**Comment by prusnak** [comment]
trezord is a very simple application - it just forwards serialized protobuf stream from http to usb and vice versa. If you think this simple behaviour deserves tests (not sure how to test this anyway), please send a pull request.

What you are probably looking for is https://github.com/conejoninja/tesoro (trezor communication library for Go)

Officially supported is only https://github.com/trezor/python-trezor, which also contains various device tests here: https://github.com/trezor/python-trezor/tree/master/trezorlib/tests/device_tests

**Comment by rfjakob** [comment]
`trezorlib/tests/device_tests` looks pretty good, thanks for the pointer! I noticed https://github.com/conejoninja/tesoro , the idea was to avoid using it by talking to trezord-go instead. However, I'd still need the protobuf API wrappers, so...

As for what to test, the HTTP origin validation looks important and non-trivial: https://github.com/trezor/trezord-go/blob/d7497309c439f59614303d9ec713593f6846d20d/server/api/api.go#L204
