### ISSUE TITLE
Systemd Dependecy

### ISSUE THREAD

**Issue by webdvp** [trezor/trezord-go#73]
I just to want bring attention to the controversial decision to use Systemd as a dependency for running Trezor bridge on Linux. 

There are strong arguments for and against Systemd, I think it is wrong that people should be forced to install Systemd in order to use Trezor-Bridge on a Linux machine. 

Trezor-bridge is the most user freindly tool. I want to use it on Linux. Please consider making it independent of Systemd. 

Thanks

**Comment by karel-3d** [comment]
It is hard to maintain init scripts for all kind of distributions, systemd makes it far easier to maintain cross-distribution. Sorry.

The project is open source, feel free to fork it and add init script for your distribution. You can also build and run it yourself.

See similar discussion here

https://github.com/trezor/trezord-go/issues/24
