### ISSUE TITLE
Cannot install Trezor Bridge 2.0.14 on Ubuntu 18

### ISSUE THREAD

**Issue by DavidG21** [trezor/trezord-go#74]

**Comment by DavidG21** [comment]
Clicking download 64-bit - it downloads and then allows you to install bridge but it does not actually install.  Used Firefox and Chromium - neither worked.

**Comment by karel-3d** [comment]
Hey, thanks for reporting this. Can you post some screenshots so we can see
what is happening?

**Comment by DavidG21** [comment]
![screenshot from 2018-06-23 16-13-43](https://user-images.githubusercontent.com/40524387/41813700-72c871c4-7700-11e8-9d90-d1f253e83143.png)
![screenshot from 2018-06-23 16-13-23](https://user-images.githubusercontent.com/40524387/41813701-72dd3046-7700-11e8-8607-da42ffebbf00.png)
![screenshot from 2018-06-23 16-12-57](https://user-images.githubusercontent.com/40524387/41813702-72f43bba-7700-11e8-995a-2575a7e128ed.png)
![screenshot from 2018-06-23 16-11-05](https://user-images.githubusercontent.com/40524387/41813703-7309d97a-7700-11e8-9184-ecddb739c287.png)


Thanks for responding.   attached are the screen shots.   I click install and it asks me for a password to install.  I enter the password and it appears to go through the installation process but doesn't actually install.  The bridge did work on my computer when I was using Ubuntu 16 LTS.

**Comment by MARTYPAUL** [comment]
*HAVE A GREAT DAY*
*MARTY *

**Comment by prusnak** [comment]
"Download size: 0 bytes" certainly doesn't look right

**Comment by DavidG21** [comment]
Here is a screen capture of the download...  It is 2.4MB...   

 
![screenshot from 2018-06-24 11-17-29](https://user-images.githubusercontent.com/40524387/41821026-508b96e0-77a0-11e8-9b3e-5f6e63185324.png)

**Comment by prusnak** [comment]
Try installing it from the command-line `dpkg -i trezor-bridge_2.0.14_amd64.deb` and post the console output

**Comment by DavidG21** [comment]
Sorry but I was out all week.      

EXCELLENT, it this worked!  Thank you!     It must be the new installation protocol with Ubuntu 18.04.

**Comment by karel-3d** [comment]
@prusnak I tried it on my ubuntu and it also shows this `"Download size: 0 bytes" `, however it installs correctly

Ubuntu "Software Center" is buggy. :(

**Comment by DavidG21** [comment]
I think you are correct.   It is Ubuntu installation software that is the problem.
