### ISSUE TITLE
Unable to build on go =< 1.8

### ISSUE THREAD

**Issue by xaionaro** [trezor/trezord-go#80]
Some applications (for example `gocryptfs`) supports building on go 1.5-1.10. But trezord-go supports building only on 1.9-1.10. Otherwise:

```
.../usb/bus.go:14: syntax error: unexpected = in type declaration
.../usb/bus.go:15: syntax error: unexpected = in type declaration
.../usb/bus.go:16: syntax error: unexpected = in type declaration
```

In the meantime `usbhid` was moved into `trezord-go` while it (`usbhid`) was used by `conejoninja/tesoro` (used by `xaionaro-go/cryptoWallet` used by `rfjakob/gocryptfs`). So it (`gocryptfs`, `cryptoWallet` and `tesoro`) cannot pass a check of `go vet` on go 1.5-1.8, now.

Can you remove this aliases from `usb/bus.go`? IMO, it's too early for this feature to be used.

**Comment by xaionaro** [comment]
I'll prepare a Pull Request with fixes of all problems for go1.5-1.8

**Comment by karel-3d** [comment]
Ha, I did not know anyone else uses usbhid, sorry for deleting it and causing a mess, but again as I wrote elsewhere, it stopped making sense outside of trezord-go.

Btw, if someone imports `import "github.com/trezor/trezord-go/usb/lowlevel"`, it does not need to build whole trezord-go, no?

**Comment by xaionaro** [comment]
> Ha, I did not know anyone else uses usbhid, sorry for deleting it and causing a mess,

It's OK :)

> Btw, if someone imports import "github.com/trezor/trezord-go/usb/lowlevel", it does not need to build whole trezord-go, no?

Yes, but there're "vendored" packaged (that are in the `vendor/` directory). And dependency repositories are cloned fully into there. So when you run `go vet ./...` with vendored `trezord-go`, you get this error.

**Comment by karel-3d** [comment]
Oooh, linters control all vendored packages, even when they are not used directly. Makes sense!

**Comment by karel-3d** [comment]
Hm, we are using sort.Slice and that seems to be introduced in 1.8, and I don't want to add another dependency just for that...

I think requesting >=1.8 is reasonable?

**Comment by karel-3d** [comment]
Hm, we can sort by sort#Interface, but I am not sure the readability loss is worth the compatibility reasons...

**Comment by karel-3d** [comment]
I have added tests for >= 1.8 to travis, it seems to work fine. I will add that to readme too.

**Comment by xaionaro** [comment]
I'm preparing a PR. It will be ready soon :)

ATM, I've fixed building for >=go1.6.

**Comment by xaionaro** [comment]
Thank you. The problem is closed.

**Comment by karel-3d** [comment]
I will write here for example, so you see the message

The 1.5 go build now started to break

https://travis-ci.org/trezor/trezord-go/jobs/425663224

It's probably something to do with some go modules? I have no idea.

**Comment by karel-3d** [comment]
We put away the go 1.5 build.

**Comment by karel-3d** [comment]
Hey. I am now trying to rewrite trezord-go so it is more dev-friendly as a library, but ... I am not sure if the <=1.8 capability is really necessary.

Type aliasing is really useful... maybe all people already upgraded to 1.9? It's from august 2017...

**Comment by karel-3d** [comment]
Hm, I might refactor the code more so they are not needed in the end
