### ISSUE TITLE
Bridge not autostarting on Windows when non-admin account is used

### ISSUE THREAD

**Issue by PRabahy** [trezor/trezord-go#83]
Hopefully this is the correct place for this. If not, please let me know which repo is more appropriate.

Every time I reboot, I need to reinstall the trezor bridge for Armory wallet to connect. I'm not sure, but I believe that this is because I run as a non-admin user by default. When I run the installer, it does a UAC popup so that I can put in my admin account. In the last step of the installer, it launches the bridge.

My suspicion is that the non-admin user doesn't get setup to autolaunch the trezor bridge. In addition, I don't see any entry in the start menu, so I can't launch it manually.

**Comment by PRabahy** [comment]
Windows 10 Pro 64bit.

I don't see the entry for Trezor in C:\Users\[Non-Admin-Account]\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup, but there is one in C:\Users\[Admin-Account]\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup

**Comment by PRabahy** [comment]
I also just confirmed that C:\ProgramData\Microsoft\Windows\Start Menu\Programs\StartUp is empty.

**Comment by karel-3d** [comment]
See discussion in https://github.com/trezor/trezord-go/issues/91#issuecomment-419368097
