### ISSUE TITLE
Remove the intrusive changes to libusbi.h

### ISSUE THREAD

**Issue by karel-3d** [trezor/trezord-go#94]
In this PR

https://github.com/trezor/trezord-go/pull/90

I have added a field into an originally internal and opaque structure `libusb_device` in `libusbi.h` (I added `has_winusb_driver`) because I wanted to filter out devices without winusb drivers, but I was too afraid to do it directly in `windows_winusb.c`. I fear memory leaks there, since the device listing function is (1) very unreadable and complex and (2) allocates new struct for each device, but (3) run *very* often, once per 500 ms. And I included this originally un-included header in go layer and check the new field in the struct there.

The problem is that windows (and therefore, libusb) lists the composite device *before* the drivers for all its sub-devices are installed, which creates a device with no driver on the one WinUSB endpoint *while* the device driver for the winusb endpoint is installed. Writing to that device then produces an error. But the go layer cannot detect that in any way, because the libusb interfaces are too abstract.

However, my change is very intrusive and prevents from integration with other OSes - https://github.com/trezor/trezord-go/pull/70

I should probably semi-revert that change and use a different detection in the go layer. For example, somehow change the vendor ID to be different, so it is then ignored in the go layer.

**Comment by alexdupre** [comment]
Are you working on it / when do you think to have a patch?

**Comment by karel-3d** [comment]
yep starting working on it
